<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<title>Set Stats</title>

<?php
  if (!empty($_GET['NickName'])){
     $aNickName = $_GET['NickName'];
  }
?>

<SCRIPT>
var rnd = Math.random();
//-- Смена хитпоинтов
var delay = 2;          // Каждые 18сек. увеличение HP на 1%
var redHP = 0.33;       // меньше 30% красный цвет
var yellowHP = 0.66;    // меньше 60% желтый цвет, иначе зеленый
var TimerOn = -1;       // id таймера
var tkHP, maxHP;
var speed=100;
var mspeed=100;

function getCookie(Name) {
var search = Name + "="
if (document.cookie.length > 0){
  offset = document.cookie.indexOf(search)
  if (offset != -1) {
    offset += search.length
    end = document.cookie.indexOf(";", offset)
    if (end == -1) end = document.cookie.length
    return unescape(document.cookie.substring(offset, end))
  }
}
}

var MMCLUB_NICK_NAME = getCookie("MMCLUB_NICK_NAME");
var MMCLUB_SESSION = getCookie("MMCLUB_SESSION");
                               
if (MMCLUB_NICK_NAME != "<?php echo $aNickName ?>"){
   top.location.href="index.phtml";
}


function setHP(value, max, newspeed) {
  tkHP=value; maxHP=max;
  if (TimerOn>=0) { clearTimeout(TimerOn); TimerOn=-1; }
  speed=newspeed;
  setHPlocal();
}

function setHPlocal() {
  if (tkHP>maxHP) { tkHP=maxHP; }
  var sz1 = Math.round((149/maxHP)*tkHP);
  var sz2 = 150 - sz1;
  if (document.all("HP")) {
    document.HP1.width=sz1;
    document.HP2.width=sz2;
    if (tkHP/maxHP < redHP) { document.HP1.src='Items/1red.gif'; }
    else {
      if (tkHP/maxHP < yellowHP) { document.HP1.src='Items/1yellow.gif'; }
      else { document.HP1.src='Items/1green.gif'; }
    }
    var s = document.all("HP").innerHTML;
    document.all("HP").innerHTML = s.substring(0, s.lastIndexOf(':')+1) + Math.round(tkHP)+"/"+maxHP;
  }
  tkHP = (tkHP+(maxHP/100)*speed/1000);
  if (tkHP<maxHP) { TimerOn=setTimeout('setHPlocal()', delay*100); }
  else { TimerOn=-1; 
   }
}

function SetImage(iName){
    document.mainimage.src = 'Items/'+iName;
    document.F1.Pers_Image.value = iName;
}

function gotoBack(){
    location.href="char.phtml?NickName=<?php echo $aNickName; ?>";
}

</SCRIPT>


</head>

<?php
  // Узнаем характеристики персонажа
    $aWhatStat = "";
    $mysql_host = "localhost";
    $mysql_user = "root";
    $mysql_password = "";
    $my_database = "mmclub";

    $link = mysql_connect($mysql_host, $mysql_user, $mysql_password)
            or die("Could not connect : " . mysql_error());
            mysql_select_db($my_database) or die("Could not select database");
       $query = "SELECT * FROM users WHERE Nick_Name='$aNickName'";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       $aRow = mysql_fetch_array( $result);
       
       $aStrength = $aRow["Character_Strength"];
       $aEndurance = $aRow["Character_Endurance"];
       $aAccuracy = $aRow["Character_Accuracy"];
       $aDexterity = $aRow["Character_Dexterity"];
       $aNotUsedStats = $aRow["Character_UnUsed_Points"];
       $aSwordSkill = $aRow["Character_Sword"];
       $aSpearSkill = $aRow["Character_Spear"];
       $aMaceSkill = $aRow["Character_Mace"];
       $aAxeSkill = $aRow["Character_Axe"];
       $aDaggerSkill = $aRow["Character_Dagger"];

  // Меняем статы
  if (!empty($_GET['setstat']))
  {
    if ($aNotUsedStats > 0){
       $aWhatStat =  $_GET['setstat'];	
       switch ($aWhatStat){
         case "Strength":
         {  $aStrength++; $aNotUsedStats--;
            $query = "UPDATE Users SET Character_Strength=$aStrength,Character_UnUsed_Points=$aNotUsedStats WHERE Nick_Name='$aNickName'";
            break;
         }
         case "Endurance":
         {  $aEndurance++; $aNotUsedStats--;
            $query = "UPDATE Users SET Character_Endurance=$aEndurance,Character_UnUsed_Points=$aNotUsedStats WHERE Nick_Name='$aNickName'";
            break;
         }
         case "Accuracy":
         {  $aAccuracy++; $aNotUsedStats--;
            $query = "UPDATE Users SET Character_Accuracy=$aAccuracy,Character_UnUsed_Points=$aNotUsedStats WHERE Nick_Name='$aNickName'";
            break;
         }
         case "Dexterity":
         {  $aDexterity++; $aNotUsedStats--;
            $query = "UPDATE Users SET Character_Dexterity=$aDexterity,Character_UnUsed_Points=$aNotUsedStats WHERE Nick_Name='$aNickName'";
            break;
         }
       }
       $result = mysql_query($query) or die("Query failed : " . mysql_error());

    }
  }

  echo $aWhatStat;

?>

<body bgcolor="#BFBFBF" onLoad="setHP(<?php echo $aEndurance*6 ?>,
                                               <?php echo $aEndurance*6 ?>,100)">

<div align="left">
  <table border="0" width="887" cellspacing="0" cellpadding="0" bgcolor="#BFBFBF">
    <tr>
      <td width="883" height="13" valign="top" colspan="3">
        <br>
      </td>
    </tr>

    <tr>
      <td width="883" height="179" valign="top" colspan="3">
        Итак, уважаемый <b> <?php echo "$aNickName" ?> </b>, вы теперь
        полноправный житель Королевства Альтрикс и можете
        приступать к изучению мира. Однако для
        начала Вы можете распределить
        некоторые доступные характеристики
        героя, данные Вам в виде бонуса при его
        рождении.<br>
        Напротив характеристик и уровней
        мастерства владения тем или иным
        оружием есть маленький красный крестик,
        нажав на который, Вы сможете повысить
        величины вышеозначенных параметров.
        Выбирайте рассудительно, так как в
        дальнейшем Вы не сможете
        перераспределить их. Вы можете
        пропустить распределение статов, и
        сразу нажать далее, если не уверены,
        какая из характеристик более важна для
        Вашего героя, в дальнейшем Вы можете
        вернуться к распределению в меню
        Вашего рюкзака.
        <p align="center"><font color="#000080">Удачи в мире
        Альтрикса!!!</font></td>
    </tr>
    <tr>
      <td width="238" height="8" valign="top">
        <p align="center"><?php echo "$aNickName" ?>[0]</td>
      <td width="645" height="8" valign="top" colspan="2"></td>
    </tr>

   <!--  Тут размещено здоровье персонажа  -->
    <td width="238">
   <table cellspacing=0 cellpadding=0 border="0" bordercolor="#000080"><tr><td>
   <NOBR><div id=HP>
  <IMG SRC="Items/herz.gif" ALT="Уровень жизни"> <IMG SRC=1silver.gif WIDTH=1 HEIGHT=10 ALT="Уровень жизни" name=HP1><IMG SRC=1silver.gif WIDTH=1 HEIGHT=10 ALT="Уровень жизни" name=HP2>:</div>
   </nobr>
  </table>
  <!--  Конец Секции-->
  

    <tr>
      <td width="238" height="1" valign="top">
        <table border="1" width="183" height="228" cellspacing="0" cellpadding="0" bgcolor="#BFBFBF" bordercolor="#666699">
          <tr>
            <td width="27" height="32" rowspan="2" colspan="2" valign="top">&nbsp;</td>
            <td width="99" height="176" rowspan="5" valign="top" colspan="2"><img border="0" name = "mainimage" src="Items/pers.jpg"></td>
            <td width="49" height="23" colspan="2" valign="top">&nbsp;</td>
          </tr>
          <tr>
            <td width="49" height="2" colspan="2" valign="top">&nbsp;</td>
          </tr>
          <tr>
            <td width="27" height="80" colspan="2" valign="top">&nbsp;</td>
            <td width="49" height="80" colspan="2" valign="top">&nbsp;</td>
          </tr>
          <tr>
            <td width="1" height="24" valign="top">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
            <td width="25" height="24" valign="top">&nbsp;</td>
            <td width="22" height="24" valign="top">&nbsp;</td>
            <td width="26" height="24" valign="top">&nbsp;</td>
          </tr>
          <tr>
            <td width="27" height="77" colspan="2" rowspan="2" valign="top">&nbsp;</td>
            <td width="49" height="40" colspan="2" valign="top">&nbsp;</td>
          </tr>
          <tr>
            <td width="99" height="34" valign="top" colspan="2">&nbsp;</td>
            <td width="49" height="31" colspan="2" valign="top" rowspan="2">&nbsp;</td>
          </tr>
          <tr>
            <td width="27" height="1" colspan="2" valign="top">&nbsp;</td>
            <td width="44" height="3" valign="top">&nbsp;</td>
            <td width="53" height="3" valign="top">&nbsp;</td>
          </tr>
        </table>
      </td>
      <td width="252" height="1" valign="top"><font color="#000080">
        Сила: <?php echo "$aStrength"; ?>
        <?php  if ($aNotUsedStats > 0){echo '<a href="afterreg.phtml?NickName='.$aNickName.'&setstat=Strength"><img src="img/plus.gif" border=0></a>';} ?><br>
        Выносливость: <?php echo "$aEndurance"; ?>
        <?php  if ($aNotUsedStats > 0){echo '<a href="afterreg.phtml?NickName='.$aNickName.'&setstat=Endurance"><img src="img/plus.gif" border=0></a>';} ?><br>
        Точность: <?php echo "$aAccuracy"; ?>
        <?php  if ($aNotUsedStats > 0){echo '<a href="afterreg.phtml?NickName='.$aNickName.'&setstat=Accuracy"><img src="img/plus.gif" border=0></a>';} ?><br>
        Ловкость: <?php echo "$aDexterity"; ?>
        <?php  if ($aNotUsedStats > 0){echo '<a href="afterreg.phtml?NickName='.$aNickName.'&setstat=Dexterity"><img src="img/plus.gif" border=0></a>';} ?><br>
        ______________________<br>
        Опыт: 0 <br>
        Уровень: 0<br>
        Побед: 0 <br>
        Поражений: 0<br>
        Ничьих: 0<br>
        ____________<br>
        Статы: (<?php echo "$aNotUsedStats" ?>)<br>
        <p>&nbsp;
        
      </td>
      <td width="391" height="1" valign="top">
        <table border="1" width="100%">
          <tr>
            <td width="100%" colspan="3">
              <p align="center"><font face="Arial" color="#000080" size="2">Выбор
              картинки персонажа (щелкните мышью)</font></td>
          </tr>
          <tr>
            <td width="35%" valign="top" onclick="SetImage('pers1.jpg');"><img border="0" src="Items/pers1.jpg"></td>
            <td width="32%" valign="top" onclick="SetImage('pers2.jpg');"><img border="0" src="Items/pers2.jpg"></td>
            <td width="33%" valign="top" onclick="SetImage('pers3.jpg');"><img border="0" src="Items/pers3.jpg"></td>
          </tr>
          <tr>
            <td width="35%" valign="top" onclick="SetImage('pers2.jpg');"><img border="0" src="Items/pers2.jpg"></td>
            <td width="32%" valign="top" onclick="SetImage('pers3.jpg');"><img border="0" src="Items/pers3.jpg"></td>
            <td width="33%" valign="top" onclick="SetImage('pers1.jpg');"><img border="0" src="Items/pers1.jpg"></td>
          </tr>
          <tr><td><INPUT TYPE=button value="Вернуться" onclick="gotoBack()"></td></tr>
        </table>
      </td>
    </tr>
    <tr>
      <td width="238" height="1" valign="top"></td>
      <td width="645" height="1" valign="top" colspan="2">
      <form name="F1">   
          <p><input type="hidden" name="Pers_Image" value="" size="20">
      </form>    
        <p>&nbsp;</td>
    </tr>
  </table>
</div>

</body>

</html>
