<html>
<head>
<link href="menu.css" rel="stylesheet" type="text/css">
<SCRIPT LANGUAGE="JavaScript" SRC="ch2.js"></SCRIPT>

</head>
<body bgcolor="#FDFBE1">

<TEXTAREA ID="holdtext" STYLE="display:none;"></TEXTAREA>
<DIV ID=oMenu CLASS="menu" onmouseout="closeMenu()"></DIV>
<div id="mes" onclick="AddLogin()" oncontextmenu="OpenMenu()"></div>

</body>

<?php

$aIdFrom = 0;
$aIdFrom = 0;
$aMsg = '';
$AllMessages = '';
  if (!empty($_GET['NickName'])){
     $aNickName = $_GET['NickName'];
  }
  if (!empty($_GET['nameto'])){
     $aNameTo  = $_GET['nameto'];
  }
  if (!empty($_GET['msg'])){
     $aMsg  = $_GET['msg'];
  }

     // Коннект к базе
     $mysql_host = "localhost";
     $mysql_user = "root";
     $mysql_password = "";
     $my_database = "mmclub";

     $link = mysql_connect($mysql_host, $mysql_user, $mysql_password)
             or die("Could not connect : " . mysql_error());
             mysql_select_db($my_database) or die("Could not select database");
       
       
        $query = "SELECT * FROM users WHERE Nick_Name='$aNickName'";
        $result = mysql_query($query) or die("Query failed : " . mysql_error());
        $aRow = mysql_fetch_array( $result);
        $aUserFrom = $aRow["USER_ID"];
        $aBuilding = $aRow["Building"];  // какая комната (строение) ?
     if ($aMsg <> ''){
           $query = "INSERT INTO chat (CH_MSG,USER_ID,CH_ROOM) values('$aMsg','$aUserFrom','$aBuilding')";
           $result = mysql_query($query) or die("Query failed : " . mysql_error());
     }
        // покажем последние 20 сообщений чата
        $query = "SELECT u.Nick_Name, c.USER_ID_TO, c.CH_MSG FROM chat c inner join users u on u.USER_ID = c.USER_ID where CH_ROOM = '$aBuilding' or c.USER_ID_TO = '$aUserFrom' order by c.CH_ID limit 20";
        $result = mysql_query($query) or die("Query failed : " . mysql_error());
        while ($aRow = mysql_fetch_array($result)) {   
        $aUserName = $aRow["Nick_Name"];
        $aMsg = $aRow["CH_MSG"];
                  
        $AllMessages .= '<a href=\"javascript:void(0)\"><SPAN>['.$aUserName.']</SPAN></a> '.$aMsg.'<br>';
        }
        print( '<script> document.getElementById("mes").innerHTML = "'.$AllMessages.'"; </script>' );
   
  
?>

</html>
