<html>

<?php
  if (!empty($_GET['NickName'])){
     $aNickName = $_GET['NickName'];

    $aWhatStat = "";
    $aWhatSkill = "";
    // Узнаем характеристики персонажа

    $mysql_host = "localhost";
    $mysql_user = "root";
    $mysql_password = "";
    $my_database = "mmclub";

    $link = mysql_connect($mysql_host, $mysql_user, $mysql_password)
            or die("Could not connect : " . mysql_error());
            mysql_select_db($my_database) or die("Could not select database");

       $query = "SELECT b.BuildingName, u.Building FROM users u inner join Buildings b on b.id = u.Building WHERE Nick_Name='$aNickName'";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       $aRow = mysql_fetch_array( $result);
       $aRoom = $aRow["BuildingName"];
       $aBuldingID = $aRow["Building"];
       $query = "SELECT count(USER_ID) as CountUsers from users where Building = '$aBuldingID'";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       $aRow = mysql_fetch_array( $result);
       $aCountUsers = $aRow["CountUsers"];
       // пишем название комнаты и сколько там народу
       print('<b>'.$aRoom.'</b>('.$aCountUsers.')');
       $query = "SELECT Nick_Name,Character_Level from users where Building = '$aBuldingID'";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       while ($aRow = mysql_fetch_array($result)) {
           $aUser  = $aRow["Nick_Name"];
           $aLevel  = $aRow["Character_Level"];
           print($aUser.'['.$aLevel.'] <img src="img\inf.jpg"><br>');
       }
  }
?>

<body bgcolor="#E1FDE2">
</body>
</html>
