<html>
<head>

<?php 
  $aHours = date("H");
  $aMinutes = date("i");
  $aSeconds = date("s");

?>


<script>
 function rslength() // изменяет размер строки ввода текста
 {
  var size = document.body.clientWidth-(3*30)-21-59-256-18-30;
  if (size<100) { size=100 }
    document.F1.text.width = size;
    document.all('T2').width = size;
  }
window.onresize=rslength;
</script>
</head>

<body leftmargin=0 topmargin=0 marginheight=0 marginwidth=0 bgcolor=#E6E6E6 onload="rslength()">
<form action="add_to_chat.php" method="GET" name="F1" target="refreshed" id="F1">
<table width="100%" height="30" cellspacing="0" cellpadding="0">
<tr valign="top" style="background-image:url(http://mmclub.com/img/beg_chat_03.gif); background-position: top; background-repeat:repeat-x; ">
<td width="30"><img src="img/b.gif" width="30" height="30" alt="Чат" /></td>
<td valign="middle" id="T2"><input type="text" name="text" maxlength="240" size="80" onkeyup="if((event.ctrlKey) && ((event.keyCode==10)||(event.keyCode==13))) { document.F1.sbm.click() }" /></td>
<td nowrap id="T3"><img src="img/b_ok.gif" width="30" height="30" alt="Добавить текст в чат" style="cursor: hand" onclick="document.F1.sbm.click()" />
<img src="img/1x1.gif" width="8" height="1" alt="" />
<img src="img/b_clear.gif" width="30" height="30" alt="Очистить строку ввода/чат" style="cursor: hand" onclick="clearc()" />
<img src="img/b_smile.gif" width="30" height="30" alt="Смайлики" style="cursor:hand" onclick="smiles()" /></td>
<td width="19" id="T4" background="img/b_bg2.gif"><img src="img/beg_chat_05.gif" width="19" height="30" alt="" /></td>
<td align="right" nowrap="nowrap" bgcolor="BAB7B3" id="T5" background="img/b_bg2.gif">
<img src="img/a_inv.gif" width="30" height="30" alt="Настройки/Инвентарь" style="cursor:hand" onclick="top.cht('/main.phtml?edit='+Math.random())" />
<img src="img/a_friend.gif" width="30" height="30" alt="Друзья" style="cursor:hand" onclick="top.cht('/main.phtml?friends=')" />
<img src="img/a_ext.gif" width="30" height="30" alt="Выход из игры" style="cursor:hand" onclick="if (confirm('Выйти из игры?')) top.window.navigate('/main.phtml?exit=0.781520416407446')" /></td>
<td width="70" valign="middle" background="img/b_bg2.gif" bgcolor="BAB7B3" id="T6"><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0" width="70" height="26">
<param name="movie" value="img/clock.swf?<?php echo 'hours='.$aHours.'&minutes='.$aMinutes.'&sec='.$aSeconds ?>" />
<param name="quality" value="high" />
</object>
</td>
<td width="9" valign="middle" background="img/b_bg2.gif" bgcolor="BAB7B3">
</tr>
</table>
</form>
</body>
</html>