<html>

<head>
<meta http-equiv="Content-Language" content="ru">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Кузница Силлурии</title>

<?php
$aMode = 1;
$aItem = 0;      // покупаемый предмет
$aItemType = 1;  // тип предмета
if (!empty($_GET['NickName']))
{
   $aNickName = $_GET['NickName'];
}
//if (!empty($_GET['mode']))   -- зарезервировано под другие режимы (Починить, Обучиться)
//{
//   $aMode = $_GET['mode'];
//}
if (!empty($_GET['itemtype']))
{
   $aItemType = $_GET['itemtype'];
}
// Раз передан этот параметр, значит режим покупки
$iBuy = false;
if (!empty($_GET['item']))
{
   $aItem = $_GET['item'];
   $iBuy = true;
}

?>

</head>

<body bgcolor=e2e0e0>


<?php
     // Коннект к базе
     $mysql_host = "localhost";
     $mysql_user = "root";
     $mysql_password = "";
     $my_database = "mmclub";
     
     $link = mysql_connect($mysql_host, $mysql_user, $mysql_password)
             or die("Could not connect : " . mysql_error());
             mysql_select_db($my_database) or die("Could not select database");

     // Сколько денег у перса
     $query = "SELECT * FROM users WHERE Nick_Name='$aNickName'";
     $result = mysql_query($query) or die("Query failed : " . mysql_error());
     $aRow = mysql_fetch_array( $result);
     $aUserID = $aRow["USER_ID"];
     $aMoney = $aRow["Character_Money"];


 if ($iBuy){    // Была инициирована покупка

     // Сколько вещей этого типа?
     $query = "SELECT s.SM_ID,s.QTY,il.Item_StateCost,il.ItemName,il.ItemType,il.ItemNo FROM smith s inner join Items_List il on s.IL_ID=il.IL_ID WHERE il.IL_ID = '$aItem'";
     $result = mysql_query($query) or die("Query failed : " . mysql_error());
     $aRow = mysql_fetch_array( $result);
     $aSMID      = $aRow["SM_ID"];
     $aQTY       = $aRow["QTY"];
     $aStateCost = $aRow["Item_StateCost"];
     $aItemName  = $aRow["ItemName"];

     if ($aQTY-- > -1){   // есть ли вообще эти вещи?
        $lNoMoney=false;
        if ($aMoney >= $aStateCost){   // хватит ли денег купить вещь?
           $aMoney = $aMoney - $aStateCost;
           // Засунем в рюкзак купленную вещь!
           $query = "INSERT INTO items(IL_ID,Item_Owner,Item_Position,Item_CurrentLife)";
           $query .= "Values ('$aItem','$aUserID','2','0')";
           $result = mysql_query($query,$link) or die("Query failed : " . mysql_error());

           // Уменьшим деньги
           $query = "UPDATE users SET Character_Money='$aMoney' WHERE Nick_Name='$aNickName'";
           $result = mysql_query($query) or die("Query failed : " . mysql_error());
           
           // Уменьшим кол-во предметов в магазине
           $query = "UPDATE smith SET QTY='$aQTY' WHERE SM_ID='$aSMID'";
           $result = mysql_query($query) or die("Query failed : " . mysql_error());

        }else
        {
           $lNoMoney=true;
        }
     }
 }
?>

<div align="center">
  <center>
  <table border="1" width="985" height="115" cellspacing="0" cellpadding="0">
    <tr>
      <td width="863" height="115" rowspan="2" valign="top">
        <p align="center"><font face="Arial"><b>Кузница Силлурии</b> (открыта
        с 7.20 до 16.30)<br></font>
        <font size=2 color=red><div id="mes">             </div></font>
        <table border="1" width="80%">

          <?php
            if ($iBuy){    // Была инициирована покупка
               if($lNoMoney){
                  print("<SCRIPT>document.all('mes').innerHTML='К сожалению у Вас больше нет денег!';</SCRIPT>");
               }
               else
               {
                  print("<SCRIPT>document.all('mes').innerHTML='Вы успешно приобрели предмет: $aItemName';</SCRIPT>");
               }
            }


          // Отобразим содержимое магазина у кузнеца (оружейника)
          $query = "SELECT il.IL_ID, il.ItemName, il.ItemType, il.ItemNo, il.Item_Image, il.Item_StateCost, s.QTY FROM smith s inner join Items_List il on s.IL_ID=il.IL_ID WHERE il.ItemType='$aItemType'";
          $result = mysql_query($query) or die("Query failed : " . mysql_error());
          while ($aRow = mysql_fetch_array($result)) {
             $aItem      = $aRow["IL_ID"];
             $aItemType  = $aRow["ItemType"];
             $aItemNo    = $aRow["ItemNo"];
             $aItemQty   = $aRow["QTY"];
             $aItemImage = $aRow["Item_Image"];
             $aStateCost = $aRow["Item_StateCost"];
             $aItemName  = $aRow["ItemName"];

             print('<tr>');
             print('<td width="10%" valign="top"><img src=Items/'.$aItemImage);
             print("><br><a href=smith.phtml?NickName=$aNickName&itemtype=$aItemType&item=$aItem>купить</a></td>");
             print('<td width="90%" valign="top" bgcolor=eae0e0>'.$aItemName.'<br>Стоимость: '.$aStateCost.' (количество:'.$aItemQty.')</td>');
             print('</tr>');

          }
          ?>

        </table>
      </td>

      <?php
      //if ($aMode==1){
      print( '<td width="138" height="115" rowspan="2" valign="top">' );
         print( 'Оружие:<br>' );
         print( '<a href=smith.phtml?NickName='.$aNickName.'&mode=1&itemtype=1>Булавы</a><br>' );
         print( '<a href=smith.phtml?NickName='.$aNickName.'&mode=1&itemtype=11>Мечи</a><br>' );
         print( '<a href=smith.phtml?NickName='.$aNickName.'&mode=1&itemtype=12>Топоры</a><br>' );
         print( '<a href=smith.phtml?NickName='.$aNickName.'&mode=1&itemtype=13>Копья</a><br>' );
         print( '<a href=smith.phtml?NickName='.$aNickName.'&mode=1&itemtype=14>Кинжалы</a><br>' );
         print( '<a href=smith.phtml?NickName='.$aNickName.'&mode=1&itemtype=2>Щиты</a><br>' );
         print( '<a href=smith.phtml?NickName='.$aNickName.'&mode=1&itemtype=3>Шлемы</a><br>' );
         print( '<a href=smith.phtml?NickName='.$aNickName.'&mode=1&itemtype=4>Перчатки</a><br>' );
         print( '<a href=smith.phtml?NickName='.$aNickName.'&mode=1&itemtype=7>Сапоги</a><br>' );
         print( '<a href=smith.phtml?NickName='.$aNickName.'&mode=1&itemtype=10>Броня</a><br>' );
         print('<HR>');

      print( '</td>' );
      //}
      ?>

      Деньги: <font color=red><?php echo $aMoney; ?></font> кр

      <td width="18" height="173" valign="top">
        <p align="center"><img border="0" src="Items/smith_pic.jpg" width="116" height="230"></p>
      </td>
    </tr>
    <tr>
      <td width="18" height="330" valign="top"><font face="Arial"><a href="smith.phtml?mode=1&item=1&NickName=<? echo $aNickName ?>">Купить</a><br>
        Починить<br>
        Обучиться<br>
        <a href="map.phtml?NickName=<?php echo $aNickName; ?>">
        Выйти</a></font>
        </td>
  </table>
  </center>
</div>

</body>

</html>
