<html>
<head>
<META http-equiv=content-type content="text/html; charset=windows-1251">
<LINK href="main.css" type=text/css rel=stylesheet>

<SCRIPT>
  var magic = 0;
</SCRIPT>


<?php
  $aMP = 0;  // защита от магии
  $aBattleID = 0;
  $aChar1 = "";
  $aChar2 = "";
  $aMove1 = 0;
  $aMove2 = 0;
  $aCurHealth1 = 0;
  $aCurHealth2 = 0;
  $aNickName = "";
  $aOrder = 0;          // какие мы в строке боя - CHAR1 или CHAR2 ?
  $aOpponentNick = "";  // наш оппонент
  if (!empty($_GET['NickName'])){
     $aNickName = $_GET['NickName'];
  }
  if (!empty($_POST['NickName'])){
     $aNickName = $_POST['NickName'];
  }
  if ($aNickName <> ""){
    $aWhatStat = "";
    $aWhatSkill = "";
    // Узнаем характеристики персонажа

    $mysql_host = "localhost";
    $mysql_user = "root";
    $mysql_password = "";
    $my_database = "mmclub";

    $link = mysql_connect($mysql_host, $mysql_user, $mysql_password)
            or die("Could not connect : " . mysql_error());
            mysql_select_db($my_database) or die("Could not select database");

       // узнаем каким номером мы находимсяя в строке боя CHAR1 или CHAR2, кто наш противник
       // и кто уже успел сделать ход ?
       $query = "SELECT BAT_ID,CHAR1_NAME,CHAR2_NAME,M1,M2 FROM battle WHERE CHAR1_NAME='$aNickName' OR CHAR2_NAME='$aNickName'";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       $aRow = mysql_fetch_array( $result);
       $aBattleID = $aRow["BAT_ID"];
       $aChar1 = $aRow["CHAR1_NAME"];
       $aChar2 = $aRow["CHAR2_NAME"];
       $aMove1 = $aRow["M1"];
       $aMove2 = $aRow["M2"];
       
       // определим некоторые параметры char1 и char2
       // 1
       $query = "SELECT * FROM users WHERE Nick_Name='$aChar1'";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       $aRow = mysql_fetch_array( $result);
       $aStrength1 = $aRow["Character_Strength"];
       $aEndurance1 = $aRow["Character_Endurance"];
       $aCurHealth1 = $aRow["Character_CurHealth"];
       $aCurMana1 = $aRow["Character_CurMana"];    // добавили в уроке 9
       $aMaxMana1 = $aRow["Character_MaxMana"];    // добавили в уроке 9
       $aScroll_Slot1  = $aRow["Scroll_Slot"];      // добавили в уроке 9  (для свитков)
       $aMP1  = $aRow["Character_Magic_Protection"];      // добавили в уроке 9.5.

       // 2
       $query = "SELECT * FROM users WHERE Nick_Name='$aChar2'";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       $aRow = mysql_fetch_array( $result);
       $aStrength2 = $aRow["Character_Strength"];
       $aEndurance2 = $aRow["Character_Endurance"];
       $aCurHealth2 = $aRow["Character_CurHealth"];
       $aCurMana2 = $aRow["Character_CurMana"];    // добавили в уроке 9
       $aMaxMana2 = $aRow["Character_MaxMana"];    // добавили в уроке 9
       $aScroll_Slot2  = $aRow["Scroll_Slot"];      // добавили в уроке 9  (для свитков)
       $aMP2  = $aRow["Character_Magic_Protection"];      // добавили в уроке 9.5.

       // Поединок закончен ?
       if ( ($aCurHealth1 == 0) || ($aCurHealth2 == 0) ){
          // Устанавливаем статус 3 (чтоб посмотреть результаты) и убираем маг.защиту, если была (9.5.)
          $query = "UPDATE users set Character_Status = 3,Character_Magic_Protection=0 where Nick_Name='$aChar1' or Nick_Name='$aChar2'";
          $result = mysql_query($query) or die("Query failed : " . mysql_error());
          // установим статусы после боя, согласно сохранившегося здоровья
          $query = "UPDATE battle set R1=$aCurHealth1,R2=$aCurHealth2 where CHAR1_NAME='$aChar1' or CHAR2_NAME='$aChar2'";
          $result = mysql_query($query) or die("Query failed : " . mysql_error());

          print('<SCRIPT>location.href="wait.phtml?NickName='.$aNickName.'&bat_id='.$aBattleID.'";</SCRIPT>');
       }


       if ( $aNickName == $aChar1 ){       //  Мы под первым номером

          $aShowEndurance1 = $aEndurance1;
          $aShowHealth1    = $aCurHealth1;
          $aShowEndurance2 = $aEndurance2;
          $aShowHealth2    = $aCurHealth2;

          $aShowCurMana = $aCurMana1;       // добавили в уроке 9
          $aShowMaxMana = $aMaxMana1;       // добавили в уроке 9
          $aShowScroll_Slot = $aScroll_Slot1;   // добавили в уроке 9  (для свитков)
          $aMP = $aMP1;

          $aOrder = 1;
          $aOpponentNick = $aChar2;
          // Проверим походил ли соперник
          if (($aMove1 == 1) & ($aMove2 == 0)){
              print('<SCRIPT>location.href="wait.phtml?NickName='.$aNickName.'&bat_id='.$aBattleID.'";</SCRIPT>');
          }
          if ($aMove1 == 0){
             // мы сделали ход!
             if (!empty($_POST['attack'])) {
                $aAttack = $_POST['attack'];
                $aDefend = $_POST['defend'];
                $query = "INSERT INTO battledetails(BAT_ID,CHAR_NAME,ATTACK,DEFEND) values ($aBattleID,'$aNickName',$aAttack,$aDefend)";
                $result = mysql_query($query) or die("Query failed : " . mysql_error());
                // установим флаг хода для 1 игрока
                $query = "UPDATE battle set M1=1 where CHAR1_NAME='$aNickName'";
                $result = mysql_query($query) or die("Query failed : " . mysql_error());
                print('<SCRIPT>location.href="battle.phtml?NickName='.$aNickName.'";</SCRIPT>');
             }
          }
          if (($aMove1 == 1) & ($aMove2 == 1)){              // расчитываем damage для обоих персонажей
              CalcDamage($aChar1,$aChar2,$aBattleID);        // считаем повреждения
              print('<SCRIPT>location.href="battle.phtml?NickName='.$aNickName.'";</SCRIPT>');
          }

       } else {                           // Мы под вторым номером
          $aShowEndurance1 = $aEndurance2;
          $aShowHealth1    = $aCurHealth2;
          $aShowEndurance2 = $aEndurance1;
          $aShowHealth2    = $aCurHealth1;

          $aShowCurMana = $aCurMana2;       // добавили в уроке 9
          $aShowMaxMana = $aMaxMana2;       // добавили в уроке 9
          $aShowScroll_Slot = $aScroll_Slot2;   // добавили в уроке 9  (для свитков)
          $aMP = $aMP2;
          
          $aOrder = 2;
          $aOpponentNick = $aChar1;
          if (($aMove2 == 1) & ($aMove1 == 0)){
              print('<SCRIPT>location.href="wait.phtml?NickName='.$aNickName.'&bat_id='.$aBattleID.'";</SCRIPT>');
          }
          if ($aMove2 == 0){
             // мы сделали ход!
             if (!empty($_POST['attack'])) {
                $aAttack = $_POST['attack'];
                $aDefend = $_POST['defend'];
                $query = "INSERT INTO battledetails(BAT_ID,CHAR_NAME,ATTACK,DEFEND) values ($aBattleID,'$aNickName',$aAttack,$aDefend)";
                $result = mysql_query($query) or die("Query failed : " . mysql_error());
                // установим флаг хода для 1 игрока
                $query = "UPDATE battle set M2=1 where CHAR2_NAME='$aNickName'";
                $result = mysql_query($query) or die("Query failed : " . mysql_error());
                print('<SCRIPT>location.href="battle.phtml?NickName='.$aNickName.'";</SCRIPT>');
             }
          }
          if (($aMove1 == 1) & ($aMove2 == 1)){              // расчитываем damage для обоих персонажей
              CalcDamage($aChar1,$aChar2,$aBattleID);        // считаем повреждения
              print('<SCRIPT>location.href="battle.phtml?NickName='.$aNickName.'";</SCRIPT>');
          }
       }
       
       if ( ($aShowCurMana > 0) && ($aShowScroll_Slot <> 0) ){
          print('<SCRIPT> magic = 1; </SCRIPT>');      // отображаем полоску маны
       }

    }
    
    function CalcDamage($aChar1,$aChar2,$aBattleID){
       // обнуляем флаги ходов игроков
       $query = "UPDATE battle set M1=0, M2=0 where BAT_ID=$aBattleID";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());

       // параметры 1 игрока
       $query = "SELECT * FROM users WHERE Nick_Name='$aChar1'";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       $aRow = mysql_fetch_array( $result);
       $aStrength1 = $aRow["Character_Strength"];
       $aCharLevel = $aRow["Character_Level"];
       $aCurHealth1 = $aRow["Character_CurHealth"];
       $aMP  = $aRow["Character_Magic_Protection"];      // добавили в уроке 9.5.
       // параметры 2 игрока
       $query = "SELECT * FROM users WHERE Nick_Name='$aChar2'";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       $aRow = mysql_fetch_array( $result);
       $aStrength2 = $aRow["Character_Strength"];
       $aCharLevel2 = $aRow["Character_Level"];
       $aCurHealth2 = $aRow["Character_CurHealth"];
       $aMP  = $aRow["Character_Magic_Protection"];      // добавили в уроке 9.5.

       // кто куда ударил и что блокировал
       // первый игрок
       $query = "select * from battledetails WHERE CHAR_NAME='$aChar1' order by batdet_id DESC limit 1";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       $aRow = mysql_fetch_array( $result);
       $aAttack1 = $aRow["ATTACK"];
       $aDefend1 = $aRow["DEFEND"];
       // второй игрок
       $query = "select * from battledetails WHERE CHAR_NAME='$aChar2' order by batdet_id DESC limit 1";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       $aRow = mysql_fetch_array( $result);
       $aAttack2 = $aRow["ATTACK"];
       $aDefend2 = $aRow["DEFEND"];
       // считаем повреждения, с учетом блоков
       // куда бил игрок 1 и что блокировал игрок 2 ?

       if ( ! Blocked($aAttack1,$aDefend2) ){
          if ($aAttack1 == 5){   // магический удар
            $aCurHealth2 = $aCurHealth2 - MagicDamage($aChar1,$aMP);
          }else {
            $aCurHealth2 = $aCurHealth2 - $aStrength1;
          }
          $aCurHealth2 = $aCurHealth2 < 0 ? 0 : $aCurHealth2;
          $query = "UPDATE users set Character_CurHealth=$aCurHealth2 where Nick_Name='$aChar2'";
          $result = mysql_query($query) or die("Query failed : " . mysql_error());
       }
       // куда бил игрок 2 и что блокировал игрок 1 ?
       if ( ! Blocked($aAttack2,$aDefend1) ){
          if ($aAttack2 == 5){   // магический удар
            $aCurHealth1 = $aCurHealth1 - MagicDamage($aChar2,$aMP);
          }else {
            $aCurHealth1 = $aCurHealth1 - $aStrength2;
          }
          $aCurHealth1 = $aCurHealth1 < 0 ? 0 : $aCurHealth1;
          $query = "UPDATE users set Character_CurHealth=$aCurHealth1 where Nick_Name='$aChar1'";
          $result = mysql_query($query) or die("Query failed : " . mysql_error());
       }
    }
    
    // посчитаем урон от магической атаки
    function MagicDamage( $aChar,$aMProt ){
       // узнаем что за свиток в слоте
       $query = "SELECT * FROM users WHERE Nick_Name='$aChar'";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       $aRow = mysql_fetch_array( $result);
       $aCurMana = $aRow["Character_CurMana"];
       $aSlotItemID  = $aRow["Scroll_Slot"];
       $query = "SELECT il.ManaCost, il.Min_Damage FROM Items it inner join Items_List il on il.il_id=it.il_id WHERE it.IT_ID='$aSlotItemID'";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       $aRow = mysql_fetch_array( $result);
       $aManaCost = $aRow["ManaCost"];
       $aMin_Damage = $aRow["Min_Damage"];
       
       // если есть защита от магии - делим повреждение пополам (добавлено d 9.5.)
       $aMin_Damage = $aMProt==0 ? $aMin_Damage : Round($aMin_Damage/2);
       
       //print('<SCRIPT> alert(['.$aManaCost.','.$aMin_Damage.']);</SCRIPT>');
       $aCurMana = $aCurMana - $aManaCost;
       $aCurMana = $aCurMana < 0 ? 0 : $aCurMana;
       $query = "UPDATE users set Character_CurMana=$aCurMana where Nick_Name='$aChar'";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       return ($aMin_Damage);
    }
    
    function Blocked($a,$d){
     $def = array(1=>'12',2=>'23',3=>'34',4=>'41');
     if ($a <> 5){  // добавили в 9.4. 5 - магический удар не блокируется
        if( strpos($def[$d],$a) === false ){
             $retv = false;
        }else{
             $retv = true;
        }
     } else { $retv = false; }
        return ($retv);
    }
    
?>
<SCRIPT>

function setattack(a){
  document.getElementById('attack').value = a;
}

function setdefend(d){
  document.getElementById('defend').value = d;
}

function checksubmit(){
  if ( (document.getElementById('attack').value == "0") ||
       (document.getElementById('defend').value == "0")){
        alert("Определитесь с атакой и защитой!");
        return false;
  }
  document.battleform.submit();
}

function getCookie(Name) {
var search = Name + "="
if (document.cookie.length > 0){
  offset = document.cookie.indexOf(search)
  if (offset != -1) {
    offset += search.length
    end = document.cookie.indexOf(";", offset)
    if (end == -1) end = document.cookie.length
    return unescape(document.cookie.substring(offset, end))
  }
}
}

var MMCLUB_NICK_NAME = getCookie("MMCLUB_NICK_NAME");
var MMCLUB_SESSION = getCookie("MMCLUB_SESSION");
                               
if (MMCLUB_NICK_NAME != "<?php echo $aNickName ?>"){
   top.location.href="index.phtml";
}

var rnd = Math.random();

//-- Смена хитпоинтов
var delay = 2;    // Каждые 18сек. увеличение HP на 1%
var redHP = 0.33; // меньше 30% красный цвет
var yellowHP = 0.66;    // меньше 60% желтый цвет, иначе зеленый
var TimerOn = -1; // id таймера
var tkHP, maxHP;
var speed=100;
var mspeed=100;


function set_HP(){
  setHP1(<?php echo $aShowHealth1 ?>, <?php echo $aShowEndurance1*6 ?>);
  if (magic==1){
    setMP1(<?php echo $aShowCurMana ?>, <?php echo $aShowMaxMana ?>);
  }
  setHP2(<?php echo $aShowHealth2 ?>, <?php echo $aShowEndurance2*6 ?>);
}

function setHP1(value, max) {
  tkHP1=value; maxHP1=max;
  if (tkHP1>maxHP1) { tkHP1=maxHP1; }

  var sz11 = Math.round((149/maxHP1)*tkHP1);
  var sz12 = 150 - sz11;

  if (document.all("HP1")) {
    document.HP11.width=sz11;
    document.HP12.width=sz12;
    if (tkHP1/maxHP1 < redHP) { document.HP11.src='items/1red.gif'; }
    else {
      if (tkHP1/maxHP1 < yellowHP) { document.HP11.src='items/1yellow.gif'; }
      else { document.HP11.src='items/1green.gif'; }
    }
    var s = document.all("HP1").innerHTML;
    document.all("HP1").innerHTML = s.substring(0, s.lastIndexOf(':')+1) + Math.round(tkHP1)+"/"+maxHP1;
  }
}

function setMP1(value, max) {
  tkMP1=value; maxMP1=max;
  if (tkMP1>maxMP1) { tkMP1=maxMP1; }
  var sz11 = Math.round((149/maxMP1)*tkMP1);
  var sz12 = 150 - sz11;
  if (document.all("MP1")) {
    document.MP11.width=sz11;
    document.MP12.width=sz12;
    document.MP11.src='items/1blue.gif';
    var s = document.all("MP1").innerHTML;
    document.all("MP1").innerHTML = s.substring(0, s.lastIndexOf(':')+1) + Math.round(tkMP1)+"/"+maxMP1;
  }
}


function setHP2(value, max) {
  tkHP2=value; maxHP2=max;
  if (tkHP2>maxHP1) { tkHP2=maxHP1; }

  var sz21 = Math.round((149/maxHP2)*tkHP2);
  var sz22 = 150 - sz21;

  if (document.all("HP2")) {
    document.HP21.width=sz21;
    document.HP22.width=sz22;
    if (tkHP2/maxHP2 < redHP) { document.HP21.src='items/1red.gif'; }
    else {
      if (tkHP2/maxHP2 < yellowHP) { document.HP21.src='items/1yellow.gif'; }
      else { document.HP21.src='items/1green.gif'; }
    }
    var s = document.all("HP2").innerHTML;
    document.all("HP2").innerHTML = s.substring(0, s.lastIndexOf(':')+1) + Math.round(tkHP2)+"/"+maxHP2;
  }
}


</SCRIPT>
</head>


<body bgcolor="#BFBFBF" onLoad="set_HP()">
<div align="center">
  <center>
  <table height="355" cellSpacing="0" cellPadding="0" width="878" border="1" id="table1">
    <tr>
      <td width="248" height="10"><?php echo $aNickName?></td>
      <td width="334" colSpan="2" height="10"></td>
      <td width="288" bgColor="#c0c0c0" height="10"><?php echo $aOpponentNick ?></td>
    </tr>
    <tr>
      <td width="248" height="229" rowSpan="5">
   
            <!--  Тут размещено здоровье нашего персонажа  -->
            <table cellspacing=0 cellpadding=0 border="0" bordercolor="#000080"><tr><td>
            <NOBR><div id=HP1>
            <IMG SRC="items/herz.gif" WIDTH=10 HEIGHT=10 ALT="Уровень жизни"> <IMG SRC=items/1silver.gif WIDTH=1 HEIGHT=10 ALT="Уровень жизни" name=HP11><IMG SRC=items/1silver.gif WIDTH=1 HEIGHT=10 ALT="Уровень жизни" name=HP12>:</div>
            </nobr>
            </table>
            <!--  Конец Секции-->
            <?php if ( ($aShowCurMana > 0) && ($aShowScroll_Slot <> 0) ){ ?>
            <!--  Тут размещены очки магии (мана) нашего персонажа  -->
            <table cellspacing=0 cellpadding=0 border="0" bordercolor="#000080"><tr><td>
            <NOBR><div id=MP1>
            <IMG SRC="items/mana.gif" WIDTH=10 HEIGHT=10 ALT="Уровень магии"> <IMG SRC=items/1silver.gif WIDTH=1 HEIGHT=10 ALT="Уровень магии" name=MP11><IMG SRC=items/1silver.gif WIDTH=1 HEIGHT=10 ALT="Уровень магии" name=MP12>:</div>
            </nobr>
            </table>
            <?php } ?>
            <!--  Конец Секции-->

        <table border="1" width="183" height="228" cellspacing="0" cellpadding="0" bgcolor="#BFBFBF" bordercolor="#666699">
          <tr>
            <td width="27" height="32" rowspan="2" colspan="2" valign="top"><img src="items\helmet_empty.jpg"></td>
            <td width="99" height="176" rowspan="5" valign="top" colspan="2"><img border="0" name = "mainimage" src="items/pers.jpg"></td>
            <td width="49" height="23" colspan="2" valign="top"><img src="items\ear_empty.jpg"></td>
          </tr>
          <tr>
            <td width="49" height="2" colspan="2" valign="top"><img src="items\necklace_empty.jpg"></td>
          </tr>
          <tr>
            <td width="27" height="80" colspan="2" valign="top"><img src="items\weapon_empty.jpg"></td>
            <td width="49" height="80" colspan="2" valign="top"><img src="items\shield_empty.jpg"></td>
          </tr>
          <tr>
            <td width="1" height="24" valign="top"><img src="items\ring_empty.jpg"></td>
            <td width="25" height="24" valign="top"><img src="items\ring_empty.jpg"></td>
            <td width="22" height="24" valign="top"><img src="items\ring_empty.jpg"></td>
            <td width="26" height="24" valign="top"><img src="items\ring_empty.jpg"></td>
          </tr>
          <tr>
            <td width="27" height="77" colspan="2" rowspan="2" valign="top"><img src="items\armor_empty.jpg"></td>
            <td width="49" height="40" colspan="2" valign="top"><img src="items\gloves_empty.jpg"></td>
          </tr>
          <tr>
            <td width="99" height="34" valign="top" colspan="2">&nbsp;</td>
            <td width="49" height="31" colspan="2" valign="top" rowspan="2"><img src="items\shoes_empty.jpg"></td>
          </tr>
          <tr>
            <td width="27" height="1" colspan="2" valign="top"><img src="items\belt_empty.jpg"></td>
            <td width="44" height="3" valign="top">&nbsp;</td>
            <td width="53" height="3" valign="top">&nbsp;</td>
          </tr>
        </table>

        <? if ($aMP == 1) { print( "Защита от магии <img src='Items/vial1.jpg' width=16 height=16 alt='Магия причиняет нам только половину вреда'>"); } ?>
        
      <p>&nbsp;</td>
      <td vAlign="top" width="334" colSpan="2" height="54">&nbsp;</td>
      <td width="288" bgColor="#c0c0c0" height="229" rowSpan="5">

            <!--  Тут размещено здоровье оппонента  -->
            <table cellspacing=0 cellpadding=0 border="0" bordercolor="#000080"><tr><td>
            <NOBR><div id=HP2>
            <IMG SRC="items/herz.gif" WIDTH=10 HEIGHT=10 ALT="Уровень жизни"> <IMG SRC=items/1silver.gif WIDTH=1 HEIGHT=10 ALT="Уровень жизни" name=HP21><IMG SRC=items/1silver.gif WIDTH=1 HEIGHT=10 ALT="Уровень жизни" name=HP22>:</div>
            </nobr>
            </table>
            <!--  Конец Секции-->

        <table border="1" width="183" height="228" cellspacing="0" cellpadding="0" bgcolor="#BFBFBF" bordercolor="#666699">
          <tr>
            <td width="27" height="32" rowspan="2" colspan="2" valign="top"><img src="items\helmet_empty.jpg"></td>
            <td width="99" height="176" rowspan="5" valign="top" colspan="2"><img border="0" name = "mainimage" src="items/pers.jpg"></td>
            <td width="49" height="23" colspan="2" valign="top"><img src="items\ear_empty.jpg"></td>
          </tr>
          <tr>
            <td width="49" height="2" colspan="2" valign="top"><img src="items\necklace_empty.jpg"></td>
          </tr>
          <tr>
            <td width="27" height="80" colspan="2" valign="top"><img src="items\weapon_empty.jpg"></td>
            <td width="49" height="80" colspan="2" valign="top"><img src="items\shield_empty.jpg"></td>
          </tr>
          <tr>
            <td width="1" height="24" valign="top"><img src="items\ring_empty.jpg"></td>
            <td width="25" height="24" valign="top"><img src="items\ring_empty.jpg"></td>
            <td width="22" height="24" valign="top"><img src="items\ring_empty.jpg"></td>
            <td width="26" height="24" valign="top"><img src="items\ring_empty.jpg"></td>
          </tr>
          <tr>
            <td width="27" height="77" colspan="2" rowspan="2" valign="top"><img src="items\armor_empty.jpg"></td>
            <td width="49" height="40" colspan="2" valign="top"><img src="items\gloves_empty.jpg"></td>
          </tr>
          <tr>
            <td width="99" height="34" valign="top" colspan="2">&nbsp;</td>
            <td width="49" height="31" colspan="2" valign="top" rowspan="2"><img src="items\shoes_empty.jpg"></td>
          </tr>
          <tr>
            <td width="27" height="1" colspan="2" valign="top"><img src="items\belt_empty.jpg"></td>
            <td width="44" height="3" valign="top">&nbsp;</td>
            <td width="53" height="3" valign="top">&nbsp;</td>
          </tr>
        </table>


      <p>&nbsp;</td>
    </tr>
    <form name="battleform" method="post" action="battle.phtml">
      <tr>
        <td vAlign="top" borderColor="#0000ff" width="167" height="15">
        Атака</td>
        <td vAlign="top" borderColor="#0000ff" width="165" height="15">
        Защита</td>
      </tr>
      <tr>
        <td vAlign="top" width="167" height="156"><font size="2">
        <input id="A11" onclick="setattack(1)" type="radio" value="1" name="att">в голову<br>
        <input id="A12" onclick="setattack(2)" type="radio" value="2" name="att">в корпус<br>
        <input id="A13" onclick="setattack(3)" type="radio" value="3" name="att">в пояс<br>
        <input id="A14" onclick="setattack(4)" type="radio" value="4" name="att">в ноги<br>
        <?php if ( ($aShowCurMana > 0) && ($aShowScroll_Slot <> 0) ){ ?>
        <input id="A15" onclick="setattack(5)" type="radio" value="5" name="att"><font color="green">удар магии</font><br>
        <?php } ?>
                &nbsp;</font><p><font size="2">&nbsp;</font></td>
        <td vAlign="top" borderColor="#0000ff" width="165" height="156">
        <font size="2">
        <input id="D11" onclick="setdefend(1)" type="radio" value="1" name="def">голова корпус<br>
        <input id="D12" onclick="setdefend(2)" type="radio" value="2" name="def">корпус пояс<br>
        <input id="D13" onclick="setdefend(3)" type="radio" value="3" name="def">пояс ноги<br>
        <input id="D14" onclick="setdefend(4)" type="radio" value="4" name="def">ноги голова</font>
        <p>&nbsp; </td>
      </tr>
      <tr>
        <td vAlign="top" width="334" colSpan="2" height="26">
                <input type="hidden" id="attack" name="attack" value="0" size="20">
                <input type="hidden" id="defend" name="defend" value="0" size="20">
                <input type="hidden" id="NickName" name="NickName" value="<?php echo $NickName ?>" size="20">
        <p align="center">
        <input type="button" value="Вперед" name="forward" onClick="checksubmit()">
        </td>
      </tr>
    </form>
    <tr>
      <td vAlign="top" width="334" colSpan="2" height="51">&nbsp;</td>
    </tr>
    <tr>
      <td width="870" height="34" colspan="4">Результат: 
      <div id="mes">&nbsp;</div>
      </td>
    </tr>
  </table>
  </center></div>

</body>

</html>
