<html>
<head>
<META http-equiv=content-type content="text/html; charset=windows-1251">
<LINK href="main.css" type=text/css rel=stylesheet>

<?php

  $lNoMoney = false;
  $aItemId = 0;
  $aTicketId = 0;
  $aSell = 0;
  if (!empty($_GET['NickName'])){
     $aNickName = $_GET['NickName'];
  }
  print ( '>>> '.$aNickName );
  
?>



</head>


<body bgcolor="#e2e0e0">
<div align="center">
  <center>
  <table border="1" width="985" height="115" cellspacing="0" cellpadding="0">
    <tr>
      <td width="863" height="115" rowspan="2" valign="top">
        <br><p align="left"><font face="Arial"><b>ТОРГОВЫЕ РЯДЫ</b><br><br></font>
        <font size=2 color=red><div id="mes">             </div></font>

<?php

    // Узнаем характеристики персонажа

    $mysql_host = "localhost";
    $mysql_user = "root";
    $mysql_password = "";
    $my_database = "mmclub";

    $link = mysql_connect($mysql_host, $mysql_user, $mysql_password)
            or die("Could not connect : " . mysql_error());
            mysql_select_db($my_database) or die("Could not select database");
      
       $query = "SELECT Town, Character_Money, USER_ID from users WHERE Nick_Name='$aNickName'";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       $aRow = mysql_fetch_array( $result);
       $aUserID = $aRow["USER_ID"];   // ID нашего игрока
       $aTown = $aRow["Town"];        // узнаем город
       $aMoney = $aRow["Character_Money"];

    
?>

      </td>
      Деньги: <font color=red><?php echo $aMoney; ?></font> кр

      <td width="18" height="173" valign="top">
        <p align="center"><img border="0" src="items/market_pic.jpg"></p>
      </td>
    </tr>
    <tr>
      <td width="18" height="100" valign="top">
        <a href="market.phtml?buy=1&NickName=<?php echo $aNickName; ?>">Прием/Передача</a></font>
        <a href="map.phtml?&NickName=<?php echo $aNickName; ?>">Выйти</a></font>
        </td>
  </table>
  </center>
</div>
    

</body>
</html>
