<html>
<head>
<META http-equiv=content-type content="text/html; charset=windows-1251">
<LINK href="main.css" type=text/css rel=stylesheet>

</head>

<body>

<CENTER>
<FORM name=log_in action=login.phtml method=post>
    <p><img border="0" src="img/logo.gif"><br>
&nbsp;</p>
    <TABLE width=200 cellSpacing=5 cellPadding=0 border=0 style="border-style: dashed; border-width: 1px" bgcolor="#FFE5B6">
    <TR>
    <TD>Логин:</TD>
    <TD><INPUT  name=login></TD>
    </TR>
    <TR>
    <TD>Пароль:</TD>
    <TD><INPUT type=password name=pass>
    </TD>
    </TR>
    <TR>
    <TD>          
    <INPUT class=loginButton type=submit value=Вход name=sbm></p>
    </TD>
    <TD style="PADDING-BOTTOM: 10px" width="99%"><A href="reg.phtml">Зарегистрироваться</A>
    </TD>
    </TR>
    </TABLE>
</FORM>

</CENTER>
</body>
</html>
