<html>
<head>
<META http-equiv=content-type content="text/html; charset=windows-1251">
<LINK href="main.css" type=text/css rel=stylesheet>

<?php
  if (!empty($_GET['NickName'])){
     $aNickName = $_GET['NickName'];
  }else{
     $aNickName = '1234';
  }
  print('Вы зашли как: '.$aNickName); 
?>

<SCRIPT>

function getCookie(Name) {
var search = Name + "="
if (document.cookie.length > 0){
  offset = document.cookie.indexOf(search)
  if (offset != -1) {
    offset += search.length
    end = document.cookie.indexOf(";", offset)
    if (end == -1) end = document.cookie.length
    return unescape(document.cookie.substring(offset, end))
  }
}
}

var MMCLUB_NICK_NAME = getCookie("MMCLUB_NICK_NAME");
var MMCLUB_SESSION = getCookie("MMCLUB_SESSION");

if (MMCLUB_NICK_NAME != "<?php echo $aNickName ?>"){
   location.href="index.phtml";
}
</SCRIPT>
</head>

<?php
print( '<frameset rows="62%, *, 30, 0" FRAMEBORDER="0" BORDER="0" FRAMESPACING="1">' );
print( '<frame name="main" src="char.phtml?UID='.$aNickName.'">' );
print(  '<frameset cols="*,180">' );
print(  '<frame name="chat" src="chat.html" target="_top" scrolling=YES FRAMEBORDER="0" BORDER="0" FRAMESPACING="0" MARGINWIDTH="3" MARGINHEIGHT="3">' );
print(  '<frame name="online" src="ch-online.html" target="_blank" scrolling=YES FRAMEBORDER=0 BORDER=0 FRAMESPACING=0 MARGINWIDTH=3 MARGINHEIGHT=0>' );
print(  '</frameset>' );
print(  '<frame name="bottom" scrolling="no" noresize src="buttons.html">' );
print(  '<frame name="refreshed" target="_top" scrolling="no" noresize src="refreshed.html">' );
print(  '</frameset>' );
?>


</html>
