<HTML>

<head>
<style>
    IMG.aFilter { filter:Glow(color=#39DAC9,Strength=4,Enabled=0); cursor:hand }
</style>


<?php
if (!empty($_GET['NickName']))
{
$aNickName = $_GET['NickName'];
}
else
{
// На стартовую
print( '<SCRIPT>top.location.href="index.html";</SCRIPT>' );

}
?>


<SCRIPT>
function imover(im)
{im.filters.Glow.Enabled=true;}
function imout(im)
{im.filters.Glow.Enabled=false;}

function gotoArena()
{
   location.href='char.phtml?NickName=<?php
                                       echo "$aNickName"; ?>';
}

function gotoWest()
{
   location.href='map.phtml?NickName=<?php
                                       echo "$aNickName"; ?>';
}


function getCookie(Name) {
var search = Name + "="
if (document.cookie.length > 0){
  offset = document.cookie.indexOf(search)
  if (offset != -1) {
    offset += search.length
    end = document.cookie.indexOf(";", offset)
    if (end == -1) end = document.cookie.length
    return unescape(document.cookie.substring(offset, end))
  }
}
}

var MMCLUB_NICK_NAME = getCookie("MMCLUB_NICK_NAME");
var MMCLUB_SESSION = getCookie("MMCLUB_SESSION");
                               
if (MMCLUB_NICK_NAME != "<?php echo $aNickName ?>"){
   top.location.href="index.phtml";
}

</SCRIPT>
</head>

<body leftmargin=0 topmargin=0 marginwidth=0 marginheight=0 bgcolor=e2e0e0>

<CENTER>

  <div style="position:relative;"><IMG SRC=Items/Towns/Silluria/map1.jpg ALT="Силлурия - столица королевства Альтрикс" width="769" height="541">
  <div style="position:absolute; left:10px; top:10px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/silluria.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" ALT="Вы находитесь в столице Королевства Альтрикс"></div>

  <div style="position:absolute; left:649px; top:170px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/sign.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" onclick="gotoWest()" ALT="В восточную часть города"></div>
  <div style="position:absolute;left:160px;top:150px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/lake.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" ALT="Озеро" width="58" height="61" ></div>
  <div style="position:absolute;left:420px;top:160px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/forest.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)"  ALT="Лес" width="70" height="70"></div>
  <div style="position:absolute;left:320px;top:90px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/mine.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)"  ALT="Шахта" width="70" height="70"></div>
  

</CENTER>
</BODY>
</HTML>
