<html>
<META http-equiv=content-type content="text/html; charset=windows-1251">
<LINK href="main.css" type=text/css rel=stylesheet>

<SCRIPT>
   function setCookie(name, value) {
      document.cookie=name+"="+escape(value)+"; path=/";
   }
</SCRIPT>
<?php
  $mysql_host = 'localhost';
  $mysql_user = 'root';
  $mysql_password = '';
  $my_database = 'mmclub';

  if ( !empty($_GET['NickName']) )
  {
    $aNickName = $_GET['NickName'];

    $link = mysql_connect($mysql_host, $mysql_user, $mysql_password)
            or die("Could not connect : " . mysql_error());
            mysql_select_db($my_database) or die("Could not select database");

    // Узнаем статус заявки перед поединком
    $query = "SELECT * FROM zayavki where CHAR1_NAME='$aNickName'";
    $result = mysql_query($query) or die("Query failed : " . mysql_error());
    $line = mysql_fetch_array($result);
    $aChar2 = $line["CHAR2_NAME"];
    $aTimeOut = $line["ZTIMEOUT"];    // таймут
    $aType = $line["ZTYPE"];          // тип боя
    
    if( $aChar2 <> '' )               // успели отозвать запрос ?
    {
      // меняем на статус - юзеры 1 и 2 в поединке
      $query = "UPDATE users SET Character_Status=2,Character_CurHealth=Character_Endurance*6,Character_CurMana=Character_Intelligence*6,Character_MaxMana=Character_Intelligence*6 WHERE Nick_Name='$aNickName' OR Nick_Name='$aChar2'";
      $result = mysql_query($query) or die("Query failed : " . mysql_error());
      // создадим новый поединок:
      $query = "INSERT INTO BATTLE (CHAR1_NAME,CHAR2_NAME,STARTTIME,TIMEOUT,STATUS) values ('$aNickName','$aChar2',Now(),$aTimeOut,1)";
      $result = mysql_query($query) or die("Query failed : " . mysql_error());

      // удаляем заявку перед поединком
      $query = "DELETE FROM zayavki WHERE CHAR1_NAME='$aNickName'";
      $result = mysql_query($query) or die("Query failed : " . mysql_error());
      print('<SCRIPT>location.href="battle.phtml?NickName='.$aNickName.'";</SCRIPT>');
    }
    else print('<SCRIPT>location.href="zayavka.phtml?NickName='.$aNickName.'";</SCRIPT>');
  }
  else  print('<SCRIPT>location.href="login_error.html";</SCRIPT>');
?>
</html>
