<HTML>

<head>
<style>
    IMG.aFilter { filter:Glow(color=#39DAC9,Strength=4,Enabled=0); cursor:hand }
</style>


<?php

$OBJECT_TYPE = 2;    // тип данного объекта 4 для всех городов

if (!empty($_GET['NickName']))
{
$aNickName = $_GET['NickName'];

     // Коннект к базе
     $mysql_host = "localhost";
     $mysql_user = "root";
     $mysql_password = "";
     $my_database = "mmclub";

     $link = mysql_connect($mysql_host, $mysql_user, $mysql_password)
             or die("Could not connect : " . mysql_error());
             mysql_select_db($my_database) or die("Could not select database");

     $query = "SELECT * FROM users WHERE Nick_Name='$aNickName'";
     $result = mysql_query($query) or die("Query failed : " . mysql_error());
     $aRow = mysql_fetch_array( $result);
     $aUserID = $aRow["USER_ID"];
     $aUserTown = $aRow["Town"];

     //------------ добавлено в 11 уроке
     $query = "SELECT ID FROM Buildings where Town=$aUserTown and BuildingType=$OBJECT_TYPE";
     $result = mysql_query($query) or die("Query failed : " . mysql_error());
     $aRow = mysql_fetch_array( $result);
     $aObjectID = $aRow["ID"];
     // меняем комнату у игрока
     $query = "UPDATE Users SET Building=$aObjectID WHERE Nick_Name='$aNickName'";
     $result = mysql_query($query) or die("Query failed : " . mysql_error());
     // -----------

}
else
{
// На стартовую
print( '<SCRIPT>top.location.href="index.html";</SCRIPT>' );

}
?>


<SCRIPT>
function imover(im)
{im.filters.Glow.Enabled=true;}
function imout(im)
{im.filters.Glow.Enabled=false;}

function gotoArena()
{
   location.href='char.phtml?gotoarena=1&NickName=<?php
                                       echo "$aNickName"; ?>';
}

function gotoWest()
{
   location.href='map2.phtml?NickName=<?php
                                       echo "$aNickName"; ?>';
}

function gotoSmith()
{
   location.href='smith.phtml?itemtype=1&mode=1&NickName=<?php
                                       echo "$aNickName"; ?>';
}

function gotoMagicShop()
{
   location.href='magicshop.phtml?itemtype=11&mode=1&NickName=<?php
                                       echo "$aNickName"; ?>';
}

function gotoComissionShop()
{
   location.href='comission.phtml?itemtype=1&mode=1&NickName=<?php
                                       echo "$aNickName"; ?>';
}


function getCookie(Name) {
var search = Name + "="
if (document.cookie.length > 0){
  offset = document.cookie.indexOf(search)
  if (offset != -1) {
    offset += search.length
    end = document.cookie.indexOf(";", offset)
    if (end == -1) end = document.cookie.length
    return unescape(document.cookie.substring(offset, end))
  }
}
}

var MMCLUB_NICK_NAME = getCookie("MMCLUB_NICK_NAME");
var MMCLUB_SESSION = getCookie("MMCLUB_SESSION");
                               
if (MMCLUB_NICK_NAME != "<?php echo $aNickName ?>"){
   top.location.href="index.phtml";
}

</SCRIPT>
</head>

<body leftmargin=0 topmargin=0 marginwidth=0 marginheight=0 bgcolor=e2e0e0>

<CENTER>

  <div style="position:relative;"><IMG SRC=Items/Towns/Silluria/map1.jpg ALT="Силлурия - столица королевства Альтрикс" width="769" height="541">
  <div style="position:absolute; left:10px; top:10px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/silluria.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" ALT="Вы находитесь в столице Королевства Альтрикс"></div>

  <div style="position:absolute; left:-49px; top:170px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/sign.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" onclick="gotoWest()" ALT="В западную часть города"></div>
  <div style="position:absolute;left:160px;top:150px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/church.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" onclick="gotoMagicShop()" ALT="Магическая лавка" width="58" height="61" ></div>
  <div style="position:absolute;left:420px;top:160px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/arena.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)"  onclick="gotoArena()" ALT="Арена" width="70" height="70"></div>
  <div style="position:absolute;left:320px;top:230px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/smith.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)"  onclick="gotoSmith()" ALT="Кузница" width="70" height="70"></div>
  <div style="position:absolute;left:120px;top:230px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/market.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" ALT="Торговые ряды" width="70" height="70"></div>
  <div style="position:absolute;left:210px;top:310px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/fireguild.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" ALT="Гильдия огня" width="70" height="70"></div>
  <div style="position:absolute;left:590px;top:290px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/waterguild.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" ALT="Гильдия воды" width="70" height="70"></div>
  <div style="position:absolute;left:590px;top:190px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/bank.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" ALT="Банк" width="70" height="70"></div>
  <div style="position:absolute;left:370px;top:350px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/mercenary.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" ALT="Торговец" width="70" height="70"></div>
  <div style="position:absolute;left:370px;top:70px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/armor.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" onclick="gotoComissionShop()" ALT="Комиссионный магазин" width="70" height="70"></div>
  <div style="position:absolute;left:570px;top:90px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/house.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" ALT="Эксперт топора" width="70" height="70"></div>
  <div style="position:absolute;left:490px;top:390px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/house.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" ALT="Магистр булавы" width="70" height="70"></div>
  <div style="position:absolute;left:140px;top:400px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/house.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" ALT="Эксперт кожи" width="70" height="70"></div>
  <div style="position:absolute;left:70px;top:50px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/house.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" ALT="Мастер огня" width="70" height="70"></div>
  <div style="position:absolute;left:-20px;top:246px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/house.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" ALT="Магистр воды" width="70" height="70"></div>
  <div style="position:absolute;left:290px;top:150px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/house.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" ALT="Эксперт земли" width="70" height="70"></div>
  <div style="position:absolute;left:300px;top:430px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/house.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" ALT="Магистр разума" width="70" height="70"></div>
  
  

</CENTER>
</BODY>
</HTML>
