<html>
<META http-equiv=content-type content="text/html; charset=windows-1251">
<LINK href="main.css" type=text/css rel=stylesheet>

<SCRIPT>
   function setCookie(name, value) {
      document.cookie=name+"="+escape(value)+"; path=/";
   }
</SCRIPT>
<?php
  $mysql_host = 'localhost';
  $mysql_user = 'root';
  $mysql_password = '';
  $my_database = 'mmclub';

  if ((!empty($_POST['login'])) && (!empty($_POST['pass'])) )
  {
    $aNickName = $_POST['login'];
    $aUserPass = $_POST['pass'];

    $link = mysql_connect($mysql_host, $mysql_user, $mysql_password)
            or die("Could not connect : " . mysql_error());
            mysql_select_db($my_database) or die("Could not select database");

    $query = "SELECT * FROM users where Nick_Name='$aNickName' and User_Pass='$aUserPass'";
    $result = mysql_query($query) or die("Query failed : " . mysql_error());
    $line = mysql_fetch_array($result);
    $aRes = $line["Nick_Name"];
    if( $aRes === $aNickName )
    {
      $aRandVal = rand(0,1000000000);
      $query = "UPDATE users SET SessionID='$aRandVal' WHERE Nick_Name='$aNickName'";
      $result = mysql_query($query) or die("Query failed : " . mysql_error());
         print('<SCRIPT>setCookie("MMCLUB_NICK_NAME","'.$aNickName.'");</SCRIPT>');
         print('<SCRIPT>setCookie("MMCLUB_SESSION","'.$aRandVal.'");</SCRIPT>');
         print('<SCRIPT>location.href="game.phtml?NickName='.$aNickName.'";</SCRIPT>');
    }
    else print('<SCRIPT>location.href="login_error.html";</SCRIPT>');
  }
  else  print('<SCRIPT>location.href="login_error.html";</SCRIPT>');
?>
</html>
