<html>
<head>
<META http-equiv=content-type content="text/html; charset=windows-1251">
<LINK href="main.css" type=text/css rel=stylesheet>

<SCRIPT>
  var mode = 1;
</SCRIPT>

<?php
  if ( (!empty($_GET['NickName'])) && (!empty($_GET['bat_id'])) ){
    $aNickName = $_GET['NickName'];
    $aBattleID = $_GET['bat_id'];

    $aWhatStat = "";
    $aWhatSkill = "";
    // Узнаем характеристики персонажа

    $mysql_host = "localhost";
    $mysql_user = "root";
    $mysql_password = "";
    $my_database = "mmclub";

    $link = mysql_connect($mysql_host, $mysql_user, $mysql_password)
            or die("Could not connect : " . mysql_error());
            mysql_select_db($my_database) or die("Could not select database");

       $query = "SELECT * FROM users WHERE Nick_Name='$aNickName'";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       $aRow = mysql_fetch_array( $result);

       $aStrength = $aRow["Character_Strength"];
       $aEndurance = $aRow["Character_Endurance"];
       $aAccuracy = $aRow["Character_Accuracy"];
       $aDexterity = $aRow["Character_Dexterity"];
       $aNotUsedStats = $aRow["Character_UnUsed_Points"];
       $aSwordSkill = $aRow["Character_Sword"];
       $aSpearSkill = $aRow["Character_Spear"];
       $aMaceSkill = $aRow["Character_Mace"];
       $aAxeSkill = $aRow["Character_Axe"];
       $aDaggerSkill = $aRow["Character_Dagger"];
       $aCharLevel = $aRow["Character_Level"];
       $aMoney = $aRow["Character_Money"];
       // добавлено в 8 уроке (проверяем статус, в бою или нет?)
       $aCharStatus = $aRow["Character_Status"];
       $aCurHealth = $aRow["Character_CurHealth"];
       mysql_free_result($result);

       // узнаем каким номером мы находимсяя в строке боя CHAR1 или CHAR2, кто наш противник
       // не пора ли нам снова делать ход ?
       $query = "SELECT BAT_ID,CHAR1_NAME,CHAR2_NAME,M1,M2,R1,R2 FROM battle WHERE BAT_ID=$aBattleID";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       $aRow = mysql_fetch_array( $result);
       //$aBattleID = $aRow["BAT_ID"];
       $aChar1 = $aRow["CHAR1_NAME"];
       $aChar2 = $aRow["CHAR2_NAME"];
       $aMove1 = $aRow["M1"];
       $aMove2 = $aRow["M2"];
       $aChar1StatusAfterBattle = $aRow["R1"];   // осталось ли здоровье у первого после боя (если бой завершен)
       $aChar2StatusAfterBattle = $aRow["R2"];   // осталось ли здоровье у второго после боя (если бой завершен)
       $aMove2 = $aRow["M2"];

       if( $aCharStatus == 2 ){
          if ( $aNickName == $aChar1 ){       //  Мы под первым номером
             if ( $aMove1 == 0 ){
                 print('<SCRIPT>location.href="battle.phtml?NickName='.$aNickName.'";</SCRIPT>');
             }
          }
          if ( $aNickName == $aChar2 ){       //  Мы под вторым номером
             if ( $aMove2 == 0 ){
                 print('<SCRIPT>location.href="battle.phtml?NickName='.$aNickName.'";</SCRIPT>');
             }
          }
          $message = "Ожидаем хода соперника. &nbsp;";
       } else {     // бой окончен
          // Устанавливаем статус 1 (нормальное состояние)
          $query = "UPDATE users set Character_Status = 1 where Nick_Name='$aChar1' or Nick_Name='$aChar2'";
          $result = mysql_query($query) or die("Query failed : " . mysql_error());
          print('<SCRIPT> mode = 2; </SCRIPT>');
          if ( $aNickName == $aChar1 ){
            if($aChar1StatusAfterBattle>$aChar2StatusAfterBattle){
               $message = "Поединок завершен. <b>Вы победили!</b> &nbsp;";
            }elseif($aChar1StatusAfterBattle<$aChar2StatusAfterBattle){
               $message = "Поединок завершен. <b>Вы проиграли!</b> &nbsp;";
            }else{
               $message = "Поединок завершен <b>вничью</b>. &nbsp;";
            }
          }
          if ( $aNickName == $aChar2 ){
            if($aChar2StatusAfterBattle>$aChar1StatusAfterBattle){
               $message = "Поединок завершен. <b>Вы победили!</b> &nbsp;";
            }elseif($aChar2StatusAfterBattle<$aChar1StatusAfterBattle){
               $message = "Поединок завершен. <b>Вы проиграли!</b> &nbsp;";
            }else{
               $message = "Поединок завершен <b>вничью</b>. &nbsp;";
            }
          }
       }
    }
    else {
       $aNickName = 'xxxxx';
       $aBattleID = 0;

    }
?>
<SCRIPT>

function renew(){
   if( mode == 1){
      location.href='wait.phtml?NickName=<?php echo $aNickName ?>&bat_id=<?php echo $aBattleID ?>';
   }else{
      location.href='char.phtml?NickName=<?php echo $aNickName ?>';
   }
}

function getCookie(Name) {
var search = Name + "="
if (document.cookie.length > 0){
  offset = document.cookie.indexOf(search)
  if (offset != -1) {
    offset += search.length
    end = document.cookie.indexOf(";", offset)
    if (end == -1) end = document.cookie.length
    return unescape(document.cookie.substring(offset, end))
  }
}
}

var MMCLUB_NICK_NAME = getCookie("MMCLUB_NICK_NAME");
var MMCLUB_SESSION = getCookie("MMCLUB_SESSION");
                               
if (MMCLUB_NICK_NAME != "<?php echo $aNickName ?>"){
   top.location.href="index.phtml";
}

var rnd = Math.random();

//-- Смена хитпоинтов
var delay = 2;    // Каждые 18сек. увеличение HP на 1%
var redHP = 0.33; // меньше 30% красный цвет
var yellowHP = 0.66;    // меньше 60% желтый цвет, иначе зеленый
var TimerOn = -1; // id таймера
var tkHP, maxHP;
var speed=100;
var mspeed=100;

function setHP() {
  setHP1( <?php echo $aCurHealth ?>, <?php echo $aEndurance*6 ?>);
}

function setHP1(value, max) {
  tkHP1=value; maxHP1=max;
  if (tkHP1>maxHP1) { tkHP1=maxHP1; }
  var sz1 = Math.round((149/maxHP1)*tkHP1);
  var sz2 = 150 - sz1;
  if (document.all("HP")) {
    document.HP1.width=sz1;
    document.HP2.width=sz2;
    if (tkHP/maxHP < redHP) { document.HP1.src='items/1red.gif'; }
    else {
      if (tkHP/maxHP < yellowHP) { document.HP1.src='items/1yellow.gif'; }
      else { document.HP1.src='items/1green.gif'; }
    }
    var s = document.all("HP").innerHTML;
    document.all("HP").innerHTML = s.substring(0, s.lastIndexOf(':')+1) + Math.round(tkHP1)+"/"+maxHP1;
  }
}


</SCRIPT>
</head>


<body bgcolor="#BFBFBF" onLoad="setHP()">
<div align="left">
  <table border="0" width="887" cellspacing="0" cellpadding="0" bgcolor="#BFBFBF">
    <tr>
      <td width="883" height="13" valign="top" colspan="3">
      </td>
    </tr>

    <tr>
      <td width="238" height="8" valign="top">
        <p align="center"><?php echo "$aNickName [$aCharLevel]" ?></td>
      <td width="645" height="8" valign="top" colspan="2"></td>
    </tr>

   <!--  Тут размещено здоровье персонажа  -->
    <td width="238">
   <table cellspacing=0 cellpadding=0 border="0" bordercolor="#000080"><tr><td>
   <NOBR><div id=HP>
  <IMG SRC="items/herz.gif" ALT="Уровень жизни"> <IMG SRC=1silver.gif WIDTH=1 HEIGHT=10 ALT="Уровень жизни" name=HP1><IMG SRC=1silver.gif WIDTH=1 HEIGHT=10 ALT="Уровень жизни" name=HP2>:</div>
   </nobr>
  </table>
  <!--  Конец Секции-->

    <tr>
      <td width="238" height="1" valign="top">
        <table border="1" width="183" height="228" cellspacing="0" cellpadding="0" bgcolor="#BFBFBF" bordercolor="#666699">
          <tr>
            <td width="27" height="32" rowspan="2" colspan="2" valign="top"><img src="items\helmet_empty.jpg"></td>
            <td width="99" height="176" rowspan="5" valign="top" colspan="2"><img border="0" name = "mainimage" src="items/pers.jpg"></td>
            <td width="49" height="23" colspan="2" valign="top"><img src="items\ear_empty.jpg"></td>
          </tr>
          <tr>
            <td width="49" height="2" colspan="2" valign="top"><img src="items\necklace_empty.jpg"></td>
          </tr>
          <tr>
            <td width="27" height="80" colspan="2" valign="top"><img src="items\weapon_empty.jpg"></td>
            <td width="49" height="80" colspan="2" valign="top"><img src="items\shield_empty.jpg"></td>
          </tr>
          <tr>
            <td width="1" height="24" valign="top"><img src="items\ring_empty.jpg"></td>
            <td width="25" height="24" valign="top"><img src="items\ring_empty.jpg"></td>
            <td width="22" height="24" valign="top"><img src="items\ring_empty.jpg"></td>
            <td width="26" height="24" valign="top"><img src="items\ring_empty.jpg"></td>
          </tr>
          <tr>
            <td width="27" height="77" colspan="2" rowspan="2" valign="top"><img src="items\armor_empty.jpg"></td>
            <td width="49" height="40" colspan="2" valign="top"><img src="items\gloves_empty.jpg"></td>
          </tr>
          <tr>
            <td width="99" height="34" valign="top" colspan="2">&nbsp;</td>
            <td width="49" height="31" colspan="2" valign="top" rowspan="2"><img src="items\shoes_empty.jpg"></td>
          </tr>
          <tr>
            <td width="27" height="1" colspan="2" valign="top"><img src="items\belt_empty.jpg"></td>
            <td width="44" height="3" valign="top">&nbsp;</td>
            <td width="53" height="3" valign="top">&nbsp;</td>
          </tr>
        </table>
      </td>
      
      <td width="252" height="1" valign="top"><font color="#000080">
        Сила: <?php echo "$aStrength"; ?><br>
        Ловкость: <?php echo "$aDexterity"; ?><br>
        Точность: <?php echo "$aAccuracy"; ?><br>
        Выносливость: <?php echo "$aEndurance"; ?><br>
        <HR>
        Опыт: 0 <br>
        Уровень: 0<br>
        Побед: 0 <br>
        Поражений: 0<br>
        Ничьих: 0<br>
        Деньги: </font><b><font color="#FF0000"><?php echo "$aMoney"; ?></font></b> <font color="#000080">кр<br>
        <HR>
        <p>&nbsp;</font>
        
      </td>
      <td width="391" height="1" valign="top">

      <!--
      Тут будут кнопки управления и ссылки на форум, энциклопедию и т.д.
      -->
      <? echo $message ?>
      <INPUT TYPE=button value="Обновить" onclick="renew()">

      </td>
    </tr>
    <tr>
      <td width="238" height="1" valign="top"></td>
      <td width="645" height="1" valign="top" colspan="2">
      <form name="F1">   
          <p><input type="hidden" name="Pers_Image" value="" size="20">
      </form>    
        <p>&nbsp;</td>
    </tr>
  </table>
</div>

</body>

</html>
