Мы предоставляем следующие услуги:
<OL>
<LI>Открытие счета<LI>Возможность положить/снять кредиты/еврокредиты со счета
<LI>Перевести кредиты/еврокредиты с одного счета на другой
<LI>Обменный пункт. Обмен еврокредитов на кредиты
</OL>
<FORM action="bank.pl" method=POST>
Хотите открыть свой счет? Услуга платная: 3.00 кр.</B> <INPUT TYPE=submit value="Открыть счет" name=open>
</FORM>

<TABLE><TR><FORM action="bank.pl" name="F2" method=POST><TD>
<FIELDSET><LEGEND><B>Управление счетом</B> </LEGEND>
<TABLE>
<TR><TD valign=top>
<TABLE>
<TR><TD>Номер счета</td> <TD colspan=2><select name="num" size=0 style="width: 90px">
<option value="465770891">465770891</option>
</select></td></tr>
<TR><TD>Пароль</td><td> <INPUT style='width:90;' type=password value="" name=psw></td><TD style='padding: 0, 0, 3, 5'><img border=0 SRC="http://img.combats.ru/i/misc/klav_transparent.gif" style='cursor: hand' onClick="KeypadShow(1, 'F2', 'psw', 'keypad2');"></TD></tr>
<TR><TD colspan=3 align=center><INPUT TYPE=submit value="Войти" name=enter></td></tr>
</TABLE>
</TD>
<TD><div id="keypad2" align=center style="display: none;"></div></TD></TR>
</TABLE>
</FIELDSET>
</TD></TR></TABLE>
Забыли номер счета и/или пароль? Можно их выслать на email, указанный в анкете <INPUT TYPE=submit value="Выслать" name=reminder>
<br><br>
</FORM>