<HTML>

<head>
<style>
    IMG.aFilter { filter:Glow(color=#39DAC9,Strength=4,Enabled=0); cursor:hand }
</style>


<?php

$OBJECT_TYPE = 6;    // тип данного объекта 6 для всех городов

if (!empty($_GET['NickName']))
{
$aNickName = $_GET['NickName'];
}
else
{
// На стартовую
print( '<SCRIPT>top.location.href="index.html";</SCRIPT>' );
}

     // Коннект к базе
     $mysql_host = "localhost";
     $mysql_user = "root";
     $mysql_password = "";
     $my_database = "mmclub";

     $link = mysql_connect($mysql_host, $mysql_user, $mysql_password)
             or die("Could not connect : " . mysql_error());
             mysql_select_db($my_database) or die("Could not select database");

     $query = "SELECT * FROM users WHERE Nick_Name='$aNickName'";
     $result = mysql_query($query) or die("Query failed : " . mysql_error());
     $aRow = mysql_fetch_array( $result);
     $aUserID = $aRow["USER_ID"];
     $aUserTown = $aRow["Town"];

     //------------ добавлено в 11 уроке
     $query = "SELECT ID FROM Buildings where Town=$aUserTown and BuildingType=$OBJECT_TYPE";
     $result = mysql_query($query) or die("Query failed : " . mysql_error());
     $aRow = mysql_fetch_array( $result);
     $aObjectID = $aRow["ID"];
     // меняем комнату у игрока
     $query = "UPDATE Users SET Building=$aObjectID WHERE Nick_Name='$aNickName'";
     $result = mysql_query($query) or die("Query failed : " . mysql_error());
     // -----------

?>


<SCRIPT>
function imover(im)
{im.filters.Glow.Enabled=true;}
function imout(im)
{im.filters.Glow.Enabled=false;}

function gotoWest()
{
   location.href='map.phtml?NickName=<?php
                                       echo "$aNickName"; ?>';
}

function gotoBank()
{
   location.href='bank.phtml?NickName=<?php
                                       echo "$aNickName"; ?>';
}

function gotoEuro()
{
   location.href='euroshop.phtml?itemtype=120&NickName=<?php
                                       echo "$aNickName"; ?>';
}

function getCookie(Name) {
var search = Name + "="
if (document.cookie.length > 0){
  offset = document.cookie.indexOf(search)
  if (offset != -1) {
    offset += search.length
    end = document.cookie.indexOf(";", offset)
    if (end == -1) end = document.cookie.length
    return unescape(document.cookie.substring(offset, end))
  }
}
}

var MMCLUB_NICK_NAME = getCookie("MMCLUB_NICK_NAME");
var MMCLUB_SESSION = getCookie("MMCLUB_SESSION");
                               
if (MMCLUB_NICK_NAME != "<?php echo $aNickName ?>"){
   top.location.href="index.phtml";
}

</SCRIPT>
</head>

<body leftmargin=0 topmargin=0 marginwidth=0 marginheight=0 bgcolor=e2e0e0>

<CENTER>

  <div style="position:relative;"><IMG SRC=Items/Towns/Silluria/map1.jpg ALT="Силлурия - столица королевства Альтрикс" width="769" height="541">
  <div style="position:absolute; left:10px; top:10px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/silluria.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" ALT="Вы находитесь в столице Королевства Альтрикс"></div>

  <div style="position:absolute; left:649px; top:170px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/sign.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" onclick="gotoWest()" ALT="В восточную часть города"></div>
  <div style="position:absolute;left:160px;top:150px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/lake.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" ALT="Озеро" width="58" height="61" ></div>
  <div style="position:absolute;left:420px;top:160px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/forest.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)"  ALT="Лес" width="70" height="70"></div>
  <div style="position:absolute;left:320px;top:90px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/mine.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)"  ALT="Шахта" width="70" height="70"></div>
  <div style="position:absolute;left:120px;top:250px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/bank.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)"  onclick="gotoBank()" ALT="Банк" width="106" height="73"></div>
  <div style="position:absolute;left:470px;top:110px;width:149px; height:136px; z-index:12;z-index:12"><IMG SRC=Items/Towns/Silluria/euroshop.gif CLASS=aFilter onmouseover="imover(this)" onmouseout="imout(this)" onclick="gotoEuro()" ALT="Евромагазин" width="78" height="63"></div>
  

</CENTER>
</BODY>
</HTML>
