<html>
<head>
       <title>Проверка регистраци!</title>
</head>
<body>
  <?php
    $aNickName = $_POST['nickname'];
    $aPass = $_POST['pass'];
    $aFIO = $_POST['fio'];
    $aMail = $_POST['email'];
    $aYear = $_POST['year'];
    $aMonth = $_POST['month'];
    $aDay = $_POST['day'];
    $aDate = $aYear."-".$aMonth."-".$aDay;
    $aAnswer = $_POST['answer'];
    $aGender = $_POST['gender'];
    if ($aGender=='Мужской'){
      $aUserGender = 1;
    }else{
      $aUserGender = 2;
    }
    $aCity   = $_POST['city'];
    $aICQ  = $_POST['icq'];

    $mysql_host = 'localhost';
    $mysql_user = 'root';
    $mysql_password = '';
    $my_database = 'mmclub';
    $md5code       = $_POST['check'];      // md5 coded digits
    $code          = $_POST['digits'];     // real digits


   if ($md5code === md5($code)){

     $link = mysql_connect($mysql_host, $mysql_user, $mysql_password)
            or die("Could not connect : " . mysql_error());
            mysql_select_db($my_database) or die("Could not select database");

       $query = "SELECT * from users where Nick_Name = '$aNickName'";
       $result = mysql_query($query,$link) or die("Query failed : " . mysql_error());
       $num_rows = mysql_num_rows($result);
       if( $num_rows == 0 ){
         $query = "INSERT INTO users(Nick_Name,User_Pass,Full_Name,User_Birth_Day,User_EMail,Character_Birth_Day,Security_Answer,User_Gender,User_City,ICQ_Number)";
         $query .= "Values ('$aNickName','$aPass','$aFIO',Now(),'$aMail','$aDate','$aAnswer','$aUserGender','$aCity','$aICQ')";
         $result = mysql_query($query,$link) or die("Query failed : " . mysql_error());
         print("Юзер: $aNickName, с паролем: $aPass, именем: $aFIO, Датой рождения: $aDate добавлен в базу!");
       } else {
       print("Юзер: $aNickName уже есть в игре, выберите другой логин!");
       }
     mysql_close($link);
   } else {
     print("Вы ввели неправильные цифры с картинки!");    
   }
  ?>
</body>
</html>
