<html>

<head>
<meta http-equiv="Content-Language" content="ru">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<LINK href="main.css" type=text/css rel=stylesheet>
<title>Комиссионный магазин Силлурии</title>

<?php
$aMode = 1;         // по умолчанию режим просмотра групп товаров
$aBuyItem = 0;      // ID покупаемого товара
$aItemType = 1;     // тип предмета
$aItemNo = 0;       // вид предмета внутри типа
if (!empty($_GET['NickName'])){
   $aNickName = $_GET['NickName'];
}
if (!empty($_GET['itemtype'])){
   $aItemType = $_GET['itemtype'];
}
// Раз передан этот параметр, значит режим просмотра внутри категории
$iShowBuy = false;
if (!empty($_GET['itemno']))
{
   $aItemNo = $_GET['itemno'];
   $aMode = 2;
}
// Раз передан этот параметр, значит режим покупки
$iBuy = false;
if (!empty($_GET['itemid']))
{
   $aBuyItem = $_GET['itemid'];
   $iBuy = true;
}


?>

</head>

<body bgcolor=e2e0e0>


<?php
     // Коннект к базе
     $mysql_host = "localhost";
     $mysql_user = "root";
     $mysql_password = "";
     $my_database = "mmclub";
     
     $link = mysql_connect($mysql_host, $mysql_user, $mysql_password)
             or die("Could not connect : " . mysql_error());
             mysql_select_db($my_database) or die("Could not select database");

     // Сколько денег у перса
     $query = "SELECT * FROM users WHERE Nick_Name='$aNickName'";
     $result = mysql_query($query) or die("Query failed : " . mysql_error());
     $aRow = mysql_fetch_array( $result);
     $aUserID = $aRow["USER_ID"];
     $aMoney = $aRow["Character_Money"];


     if ($iBuy){    // Была инициирована покупка

        $lNoMoney=false;
        $query = "SELECT i.Item_ComissionCost,i.Item_Owner, il.ItemName FROM items i inner join Items_List il on i.il_id=il.il_id where IT_ID='$aBuyItem'";
        $result = mysql_query($query,$link) or die("Query failed : " . mysql_error());
        $aRow = mysql_fetch_array( $result);
        $aCost = $aRow["Item_ComissionCost"];   // комиссионная стоимость
        $aOwner = $aRow["Item_Owner"];          // бывший владелец предмета
        $aItemName = $aRow["ItemName"];         // название предмета из справочника

        $aShowCost = $aCost;  // стоимость в сообщении о покупке
        
        if ($aMoney >= $aCost ){   // хватит ли денег купить вещь в комиссионке?

           $aMoney = $aMoney - $aCost;
           // Засунем в рюкзак купленную вещь и поменяем владельца!
           $query = "UPDATE items SET Item_Owner=$aUserID, Item_Position=2 where IT_ID='$aBuyItem'";
           $result = mysql_query($query,$link) or die("Query failed : " . mysql_error());

           // Уменьшим наши деньги
           $query = "UPDATE users SET Character_Money=Character_Money-$aMoney WHERE Nick_Name='$aNickName'";
           $result = mysql_query($query) or die("Query failed : " . mysql_error());

           // Добавим денег предыдущему владельцу вещи с учетом комиссии 10%
           $aCost = $aCost - ($aCost*10/100);
           $query = "UPDATE users SET Character_Money=Character_Money+$aCost WHERE User_Id='$aOwner'";
           $result = mysql_query($query) or die("Query failed : " . mysql_error());

        }else
        {
           $lNoMoney=true;
        }
     }

?>

<div align="center">
  <center>
  <table border="1" width="985" height="115" cellspacing="0" cellpadding="0">
    <tr>
      <td width="863" height="115" rowspan="2" valign="top">
        <p align="center"><font face="Arial"><b>Комиссионный магазин Силлурии</b> (открыт
        с 7.00 до 16.00)<br></font>
        <font size=2 color=red><div id="mes">             </div></font>
        <table border="1" width="80%">

          <?php
            if ($iBuy){    // Была инициирована покупка
               if($lNoMoney){
                  print("<SCRIPT>document.all('mes').innerHTML='К сожалению у Вас больше нет денег!';</SCRIPT>");
               }
               else
               {
                  print("<SCRIPT>document.all('mes').innerHTML='Вы успешно приобрели предмет: $aItemName по цене: $aShowCost' ;</SCRIPT>");
               }
            }

        if ($aMode==1){
          // Отобразим содержимое магазина комиссионного магазина
          $query = "SELECT
                    count(il.ItemType) AS kolvo,
                    min(Item_ComissionCost) minc,
                    max(Item_ComissionCost) maxc,
                    il.IL_ID,
                    il.ItemName,
                    il.ItemType,
                    il.ItemNo,
                    il.Item_Image,
                    il.Item_StateCost
                    FROM
                      items i
                    INNER JOIN Items_List il ON (i.IL_ID = il.IL_ID)
                    WHERE
                      (il.ItemType = $aItemType) AND
                      (i.Item_Position = 1)
                    GROUP BY
                      il.ItemName,
                      il.ItemType,
                      il.ItemNo,
                      il.Item_Image,
                      il.Item_StateCost";
          $result = mysql_query($query) or die("Query failed : " . mysql_error());
          while ($aRow = mysql_fetch_array($result)) {
             $aKolVo     = $aRow["kolvo"];
             $aMinCost   = $aRow["minc"];
             $aMaxCost   = $aRow["maxc"];
             $aItem      = $aRow["IL_ID"];
             $aItemName  = $aRow["ItemName"];
             $aItemType  = $aRow["ItemType"];
             $aItemNo    = $aRow["ItemNo"];
             $aItemImage = $aRow["Item_Image"];
             $aStateCost = $aRow["Item_StateCost"];


             print('<tr>');
             print('<td width="10%" valign="top"><img src=Items/'.$aItemImage);
             print("><br><a href=comission.phtml?NickName=$aNickName&itemtype=$aItemType&itemno=$aItemNo>перейти</a></td>");
             print('<td width="90%" valign="top" bgcolor=eae0e0><b>'.$aItemName.'</b><br>Мин.Стоимость: <i>'.$aMinCost.'</i> Макс.Стоимость: <i>'.$aMaxCost.'</i> (количество:<b>'.$aKolVo.'</b>)</td>');
             print('</tr>');

          }
         } elseif ($aMode==2){       // режим просмотра отдельных товаров внутри группы
          // Отобразим содержимое магазина комиссионного магазина
          $query = "SELECT
                    i.Item_ComissionCost,
                    i.IT_ID,
                    il.IL_ID,
                    il.ItemName,
                    il.ItemType,
                    il.ItemNo,
                    il.Item_Image,
                    il.Item_FullLife,
                    i.Item_CurrentLife,
                    il.Item_StateCost
                    FROM
                      items i
                    INNER JOIN Items_List il ON (i.IL_ID = il.IL_ID)
                    WHERE
                      (il.ItemType = $aItemType) AND (il.ItemNo = $aItemNo) AND
                      (i.Item_Position = 1)
                      order by i.Item_ComissionCost";
          $result = mysql_query($query) or die("Query failed : " . mysql_error());
          while ($aRow = mysql_fetch_array($result)) {
             $aCost      = $aRow["Item_ComissionCost"];
             $aItem      = $aRow["IL_ID"];
             $aItemName  = $aRow["ItemName"];
             $aItemType  = $aRow["ItemType"];
             $aItemNo    = $aRow["ItemNo"];
             $aItemImage = $aRow["Item_Image"];
             $aStateCost = $aRow["Item_StateCost"];
             $aBuyItem   = $aRow["IT_ID"];
             $aItemFullLife   = $aRow["Item_FullLife"];
             $aItemCurLife   = $aRow["Item_CurrentLife"];
             print('<tr>');
             print('<td width="10%" valign="top"><img src=Items/'.$aItemImage);
             print("><br><a href=comission.phtml?NickName=$aNickName&itemtype=$aItemType&itemid=$aBuyItem>купить</a></td>");
             print('<td width="90%" valign="top" bgcolor=eae0e0><b>'.$aItemName.'</b> Долговечность: '.$aItemCurLife.'/'.$aItemFullLife.' <br>Стоимость: <i>'.$aCost.'</i></td>');
             print('</tr>');

          }
         }

         ?>

        </table>
      </td>

      <?php
      print( '<td width="138" height="115" rowspan="2" valign="top">' );
         print( 'Оружие:<br>' );
         print( '<a href=comission.phtml?NickName='.$aNickName.'&mode=1&itemtype=1>Булавы</a><br>' );
         print( '<a href=comission.phtml?NickName='.$aNickName.'&mode=1&itemtype=11>Мечи</a><br>' );
         print( '<a href=comission.phtml?NickName='.$aNickName.'&mode=1&itemtype=12>Топоры</a><br>' );
         print( '<a href=comission.phtml?NickName='.$aNickName.'&mode=1&itemtype=13>Копья</a><br>' );
         print( '<a href=comission.phtml?NickName='.$aNickName.'&mode=1&itemtype=14>Кинжалы</a><br>' );
         print( '<a href=comission.phtml?NickName='.$aNickName.'&mode=1&itemtype=2>Щиты</a><br>' );
         print( '<a href=comission.phtml?NickName='.$aNickName.'&mode=1&itemtype=3>Шлемы</a><br>' );
         print( '<a href=comission.phtml?NickName='.$aNickName.'&mode=1&itemtype=4>Перчатки</a><br>' );
         print( '<a href=comission.phtml?NickName='.$aNickName.'&mode=1&itemtype=7>Сапоги</a><br>' );
         print( '<a href=comission.phtml?NickName='.$aNickName.'&mode=1&itemtype=10>Броня</a><br>' );
         print( '<a href=comission.phtml?NickName='.$aNickName.'&mode=1&itemtype=8>Пояса</a><br>' );
         print( '<HR>' );
         print( 'Магия:<br>' );
         print( '<a href=comission.phtml?NickName='.$aNickName.'&mode=1&itemtype=11>Свитки огня</a><br>' );
         print( '<a href=comission.phtml?NickName='.$aNickName.'&mode=1&itemtype=12>Свитки воздуха</a><br>' );
         print( '<a href=comission.phtml?NickName='.$aNickName.'&mode=1&itemtype=13>Свитки воды</a><br>' );
         print( '<a href=comission.phtml?NickName='.$aNickName.'&mode=1&itemtype=14>Свитки земли</a><br>' );
         print('<HR>');
         print( 'Защита:<br>' );
         print( '<a href=comission.phtml?NickName='.$aNickName.'&mode=1&itemtype=15>Защита от магии</a><br>' );
         print('<HR>');
      print( '</td>' );

      ?>

      Деньги: <font color=red><?php echo $aMoney; ?></font> кр

      <td width="18" height="173" valign="top">
        <p align="center"><img border="0" src="Items/comission_pic.jpg"></p>
      </td>
    </tr>
    <tr>
      <td width="18" height="330" valign="top"><font face="Arial"><a href="magicshop.phtml?mode=1&item=1&NickName=<? echo $aNickName ?>">Купить</a><br>
        Обучиться<br>
        <a href="map.phtml?NickName=<?php echo $aNickName; ?>">
        Выйти</a></font>
        </td>
  </table>
  </center>
</div>

</body>

</html>
