<html>
<head>
<META http-equiv=content-type content="text/html; charset=windows-1251">
<LINK href="main.css" type=text/css rel=stylesheet>

<SCRIPT>
  var mode = 1;
</SCRIPT>

<?php

  $AStat1 = "";   // строка статистики 1 игрока    (атака)
  $AStat2 = "";   // строка статистики 2 игрока    (атака)
  $DStat1 = "";   // строка статистики 1 игрока    (защита)
  $DStat2 = "";   // строка статистики 2 игрока    (защита)

  if ( !empty($_GET['bat_id']) ){
    $aBattleID = $_GET['bat_id'];
    $aWhatStat = "";
    $aWhatSkill = "";
    // Узнаем характеристики персонажа

    $mysql_host = "localhost";
    $mysql_user = "root";
    $mysql_password = "";
    $my_database = "mmclub";

    $link = mysql_connect($mysql_host, $mysql_user, $mysql_password)
            or die("Could not connect : " . mysql_error());
            mysql_select_db($my_database) or die("Could not select database");

       //
       $query = "SELECT BAT_ID,CHAR1_NAME,CHAR2_NAME,R1,R2 FROM battle WHERE BAT_ID=$aBattleID";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       $aRow = mysql_fetch_array( $result);
       //$aBattleID = $aRow["BAT_ID"];
       $aChar1 = $aRow["CHAR1_NAME"];
       $aChar2 = $aRow["CHAR2_NAME"];
       $aChar1StatusAfterBattle = $aRow["R1"];   // осталось ли здоровье у первого после боя ?
       $aChar2StatusAfterBattle = $aRow["R2"];   // осталось ли здоровье у второго после боя ?

       // читаем статистику боя
       $query = "SELECT CHAR_NAME, ATTACK, DEFEND FROM battledetails WHERE BAT_ID=$aBattleID";
       $result = mysql_query($query) or die("Query failed : " . mysql_error());
       while ($aRow = mysql_fetch_array($result)) {
             $aChar    = $aRow["CHAR_NAME"];
             $aAttack  = $aRow["ATTACK"];
             $aDefend  = $aRow["DEFEND"];
             if ( $aChar == $aChar1 ){
                $AStat1 .= $aAttack;
                $DStat1 .= $aDefend;
             }
             if ( $aChar == $aChar2 ){
                $AStat2 .= $aAttack;
                $DStat2 .= $aDefend;
             }
       }
  }

  function Blocked($a,$d){
     $def = array(1=>'12',2=>'23',3=>'34',4=>'41');
     if( strpos($def[$d],$a) === false ){
          $retv = false;
     }else{
          $retv = true;
     }
     return ($retv);
  }



?>

</head>


<body bgcolor="#BFBFBF">

<?php print( '<font color="#6666CC"><b>'.$aChar1.'</b></font> против <font color="#B06A00"><b>'.$aChar2.'</b></font>' ) ?>

<H4><font color="#8F003F">Последовательность ударов</font></H4>
<TABLE cellSpacing=0 cellPadding=4 border=1>
  <TBODY>
  <TR>
    <TD align=middle>Логин</TD>
    <TD>Удар в</TD>
    <TD>Последовательность ударов</TD>
  </TR>
  <TR>
    <TD noWrap> <b><?php echo $aChar1 ?></b> </TD>
    <TD noWrap><PRE>голову<BR> грудь<BR> живот<BR>  ноги</PRE></TD>
    <TD noWrap>
    <?php
    print('<PRE>');
    for($i=1;$i<=4;$i++){
    $pos = 0;
    $pl = "";
    while ( $pos ++ < strlen($AStat1)){
      if( substr($AStat1,$pos,1) == $i ){
        if ( ! Blocked(substr($AStat1,$pos,1),substr($DStat2,$pos,1)) ){
           $pl.= "X";
        } else {
           $pl.= "<B>•</B>";
        }
      }else{
           $pl.= " ";
      }
    }
    print($pl);
    if( $i<>4 ) print("<BR>");
    }
    ?>
    </PRE>
    </TD>
  </TR>
  <TR>
    <TD noWrap> <b><?php echo $aChar2 ?></b></TD>
    <TD noWrap><PRE>голову<BR> грудь<BR> живот<BR>  ноги</PRE></TD>
    <TD noWrap>
    <?php
    print('<PRE>');
    for($i=1;$i<=4;$i++){
    $pos = 0;
    $pl = "";
    while ( $pos ++ < strlen($AStat2)){
      if( substr($AStat2,$pos,1) == $i ){
        if ( ! Blocked(substr($AStat2,$pos,1),substr($DStat1,$pos,1)) ){
           $pl.= "X";
        } else {
           $pl.= "<B>•</B>";
        }
      }else{
           $pl.= " ";
      }
    }
    print($pl);
    if( $i<>4 ) print("<BR>");
    }
    ?>
    </PRE></TD></TR>
  </TBODY>
  </TABLE>
  (<B>X</B>&nbsp;-&nbsp;удачный удар, <B>•</B>&nbsp;-&nbsp;соперник заблокировал)
  
<H4><font color="#8F003F">Последовательность блоков</font></H4>
<TABLE cellSpacing=0 cellPadding=4 border=1>
  <TBODY>
  <TR>
    <TD align=middle>Логин</TD>
    <TD>блок</TD>
    <TD>Последовательность блоков</TD>
  </TR>
  <TR>
    <TD noWrap> <b><?php echo $aChar1 ?></b> </TD>
    <TD noWrap><PRE>головы и груди<BR> груди и живота<BR> живота и ног<BR>  ног и головы</PRE></TD>
    <TD noWrap>
    <?php
    print('<PRE>');
    for($i=1;$i<=4;$i++){
    $pos = 0;
    $pl = "";
    while ( $pos ++ < strlen($DStat1)){
      if( substr($DStat1,$pos,1) == $i ){
        if ( ! Blocked(substr($AStat2,$pos,1),substr($DStat1,$pos,1)) ){
           $pl.= "<B>•</B>";
        } else {
           $pl.= "X";
        }
      }else{
           $pl.= " ";
      }
    }
    print($pl);
    if( $i<>4 ) print("<BR>");
    }
    ?>
    </PRE>
    </TD>
  </TR>
  <TR>
    <TD noWrap> <b><?php echo $aChar2 ?></b></TD>
    <TD noWrap><PRE>головы и груди<BR> груди и живота<BR> живота и ног<BR>  ног и головы</PRE></TD>
    <TD noWrap>
    <?php
    print('<PRE>');
    for($i=1;$i<=4;$i++){
    $pos = 0;
    $pl = "";
    while ( $pos ++ < strlen($DStat2)){
      if( substr($DStat2,$pos,1) == $i ){
        if ( ! Blocked(substr($AStat1,$pos,1),substr($DStat2,$pos,1)) ){
           $pl.= "<B>•</B>";
        } else {
           $pl.= "X";
        }
      }else{
           $pl.= " ";
      }
    }
    print($pl);
    if( $i<>4 ) print("<BR>");
    }
    ?>
    </PRE></TD></TR>
  </TBODY>
  </TABLE>
  (<B>X</B>&nbsp;-&nbsp;удачный блок, <B>•</B>&nbsp;-&nbsp;пропустил удар)

</body>

</html>
